### ISSUE TITLE
Top statistics bar settings per project

### ISSUE THREAD

**Issue by talgreen1** [ludeknovy/jtl-reporter#107]
Is it possible to add the average response time to the top statistics bar?

![Screen Shot 2021-12-07 at 14 29 32](https://user-images.githubusercontent.com/26517162/145039745-4443e5ba-3b1d-4980-95d8-66747840f958.png)

**Comment by ludeknovy** [comment]
Hi @talgreen1, it is certainly possible, but 1 metric needs to be taken away instead as there is not enough space for a certain view size. Would it make sense for you to have it customizable?

**Comment by talgreen1** [comment]
Hi, 

It would be great to have it customizable!

**Comment by ludeknovy** [comment]
@talgreen1 per user and per scenario?

**Comment by talgreen1** [comment]
Maybe for project level? In my case - I would like it to be in every project, and in every scenario.

**Comment by ludeknovy** [comment]
@talgreen1  ok, could be!

**Comment by ludeknovy** [comment]
@talgreen1  I have it ready, but need to do a bit more resting first. it is going to be released in v4.

https://user-images.githubusercontent.com/13610612/145374485-78ba5d4d-142b-473c-831c-879506e04d4a.mov

**Comment by talgreen1** [comment]
Thank you very much!!

**Comment by ludeknovy** [comment]
Available in v4.
