### ISSUE TITLE
Missing assertion message of an error request

### ISSUE THREAD

**Issue by MoritzSalein** [ludeknovy/jtl-reporter#114]
While some test runs I got assertion errors. But I'm not able to see those messages in JtlReporter. But the assertion message is stored in the jtl. E.g. the JMeter HTML Report shows this. Is it possible to show this in JtlReporter too?

![AssertionMessage](https://user-images.githubusercontent.com/83296020/151505288-db297963-171a-404e-8dcd-6db0e62902cd.png)

**Comment by ludeknovy** [comment]
Implemented.
