### ISSUE TITLE
Response Message Failures should show the HTTP status code

### ISSUE THREAD

**Issue by MoritzSalein** [ludeknovy/jtl-reporter#115]
In the health panel, it would be nice to show the HTTP status code. Because sometimes it's easier to understand the status code than the status message of an error request.

![StatusCode](https://user-images.githubusercontent.com/83296020/151506114-5f4077c8-bb0b-4951-9766-f2b16860d342.png)

**Comment by ludeknovy** [comment]
Implemented. The status code is going to be displayed only for newly uploaded and processed tests.
