### ISSUE TITLE
Performance analysis cannot be disabled

### ISSUE THREAD

**Issue by MoritzSalein** [ludeknovy/jtl-reporter#125]
The edit scenario dialogue contains the switch for performance analysis. In version 4.1 it isn't possible to save this. After submitting the dialogue you get the error `something went wrong`.

**Comment by ludeknovy** [comment]
I cannot reproduce it. Could you please send me logs from `be` service when the error occurs?

**Comment by MoritzSalein** [comment]
At the moment I can't reproduce the problem. But in the logs at the time of my problem I found the following entries:

`{"log":"{\"data\":null,\"isBoom\":true,\"isServer\":false,\"level\":\"error\",\"output\":{\"headers\":{},\"payload\":{\"error\":\"Bad Request\",\"message\":\"\\\"zeroErrorToleranceEnabled\\\" is required\",\"statusCode\":400},\"statusCode\":400}}\n","stream":"stdout","time":"2022-02-01T11:44:13.8829384Z"}
{"log":"{\"level\":\"info\",\"message\":\"PUT /api/projects/Klett/scenarios/NutzenAlt 400 9ms\",\"meta\":{}}\n","stream":"stdout","time":"2022-02-01T11:44:13.8853152Z"}`

Could this help?

**Comment by ludeknovy** [comment]
Thanks, yes, there was an invalid body sent. But unable to reproduce it anyway.

**Comment by MoritzSalein** [comment]
The problem occurred temporarily on my system. I cannot reproduce it with a newer version.
