### ISSUE TITLE
Cannot install jtlreporter_db_1 on RHEL 8.5

### ISSUE THREAD

**Issue by yobshans** [ludeknovy/jtl-reporter#126]
**Describe the bug**
I have a trouble to install jtl-reporter on RHEL 8.5
It is not clear where come timescaledb container from.
All other containers installed succefully

podman-compose up -d
using podman version: podman version 3.3.1
Error: error inspecting object: jtlreporter_db: image not known
podman build -t jtlreporter_db -f ./db/Dockerfile ./db/
STEP 1/3: FROM timescale/timescaledb:2.4.1-pg13
✔ docker.io/timescale/timescaledb:2.4.1-pg13
Trying to pull docker.io/timescale/timescaledb:2.4.1-pg13...
WARN[0036] failed, retrying in 2s ... (1/3). Error: determining manifest MIME type for docker://timescale/timescaledb:2.4.1-pg13: reading manifest sha256:f00f2c9113bcb000b1ca2491875f3eed9c02e08c7dd91a2635ad7546a4ac907a in docker.io/timescale/timescaledb: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit 
WARN[0069] failed, retrying in 2s ... (2/3). Error: initializing source docker://timescale/timescaledb:2.4.1-pg13: reading manifest 2.4.1-pg13 in docker.io/timescale/timescaledb: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit 
WARN[0103] failed, retrying in 2s ... (3/3). Error: initializing source docker://timescale/timescaledb:2.4.1-pg13: reading manifest 2.4.1-pg13 in docker.io/timescale/timescaledb: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit 
Error: error creating build container: initializing source docker://timescale/timescaledb:2.4.1-pg13: reading manifest 2.4.1-pg13 in docker.io/timescale/timescaledb: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
125

d95e72f1adcd  docker.io/novyl/jtl-reporter-be:v4.1.0                npm run start         22 minutes ago  Up 22 minutes ago          0.0.0.0:2020->80/tcp, 0.0.0.0:5000->5000/tcp, 0.0.0.0:6000->6000/tcp  jtlreporter_be_1
d79ea47b5393  docker.io/novyl/jtl-reporter-listener-service:v2.0.1  npm run start         22 minutes ago  Up 22 minutes ago          0.0.0.0:2020->80/tcp, 0.0.0.0:5000->5000/tcp, 0.0.0.0:6000->6000/tcp  jtlreporter_listener_1
67ff292c50c7  docker.io/novyl/jtl-reporter-scheduler:v0.0.2         npm run start         22 minutes ago  Up 22 minutes ago          0.0.0.0:2020->80/tcp, 0.0.0.0:5000->5000/tcp, 0.0.0.0:6000->6000/tcp  jtlreporter_scheduler_1
27221367f9cd  docker.io/novyl/jtl-reporter-be:v4.1.0                npm run migrate u...  22 minutes ago  Exited (1) 22 minutes ago  0.0.0.0:2020->80/tcp, 0.0.0.0:5000->5000/tcp, 0.0.0.0:6000->6000/tcp  jtlreporter_migration_1
fc0af3e8bb68  docker.io/novyl/jtl-reporter-fe:v4.1.1                nginx -g daemon o...  20 minutes ago  Up 20 minutes ago          0.0.0.0:2020->80/tcp, 0.0.0.0:5000->5000/tcp, 0.0.0.0:6000->6000/tcp  jtlreporter_fe_1

**To Reproduce**
git clone https://github.com/ludeknovy/jtl-reporter
cd jtl-reporter
podman-compose up -d

**Expected behavior**
Should be installed

**Screenshots**

**Additional context**
My previous attempt to install jtl-reporter succeed
But, I have a different list of containers
349bbc32712e  docker.io/novyl/jtl-reporter-be:v3.4.2                npm run start         7 weeks ago  Up 7 weeks ago  0.0.0.0:2020->80/tcp, 0.0.0.0:5000->5000/tcp, 0.0.0.0:6000->6000/tcp, 0.0.0.0:27020->27017/tcp  jtlreporter_be_1
b37880ba4736  docker.io/novyl/jtl-reporter-listener-service:v1.0.1  npm run start         7 weeks ago  Up 7 weeks ago  0.0.0.0:2020->80/tcp, 0.0.0.0:5000->5000/tcp, 0.0.0.0:6000->6000/tcp, 0.0.0.0:27020->27017/tcp  jtlreporter_listener_1
3b8011467fd2  docker.io/novyl/jtl-reporter-fe:v3.4.6                nginx -g daemon o...  7 weeks ago  Up 7 weeks ago  0.0.0.0:2020->80/tcp, 0.0.0.0:5000->5000/tcp, 0.0.0.0:6000->6000/tcp, 0.0.0.0:27020->27017/tcp  jtlreporter_fe_1
e4baed126960  docker.io/library/mongo:4.2.5-bionic                  mongod                7 weeks ago  Up 7 weeks ago  0.0.0.0:2020->80/tcp, 0.0.0.0:5000->5000/tcp, 0.0.0.0:6000->6000/tcp, 0.0.0.0:27020->27017/tcp  jtl-reporter-mongodb
3bc381db58f1  localhost/novyl/jtl-reporter-db:latest                postgres              7 weeks ago  Up 7 weeks ago  0.0.0.0:2020->80/tcp, 0.0.0.0:5000->5000/tcp, 0.0.0.0:6000->6000/tcp, 0.0.0.0:27020->27017/tcp  jtlreporter_db_1

**Did JtlReporter make you happay in any way?**
Answering this question is not required, but if you have anything positive to share, please do so here.

**Comment by yobshans** [comment]
# podman logs jtlreporter_migration_1

> jtl-reporter-be@1.0.0 migrate /src/be
> node-pg-migrate "up"

could not connect to postgres Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
}
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jtl-reporter-be@1.0.0 migrate: `node-pg-migrate "up"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jtl-reporter-be@1.0.0 migrate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-02-09T18_00_27_921Z-debug.log

**Comment by yobshans** [comment]
Tried install manually 
# podman run --name=jtl-reporter-mongodb -d --pod=jtlreporter --label io.podman.compose.config-hash=123 --label io.podman.compose.project=jtlreporter --label io.podman.compose.version=0.0.1 --label com.docker.compose.container-number=1 --label com.docker.compose.service=mongodb -e MONGO_INITDB_DATABASE=jtl-data -v /root/jtl-reporter/./data/jtl_report_mongo:/data/db -v /root/jtl-reporter/./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro --add-host fe:127.0.0.1 --add-host jtlreporter_fe_1:127.0.0.1 --add-host db:127.0.0.1 --add-host jtlreporter_db_1:127.0.0.1 --add-host mongodb:127.0.0.1 --add-host jtl-reporter-mongodb:127.0.0.1 --add-host be:127.0.0.1 --add-host jtlreporter_be_1:127.0.0.1 --add-host migration:127.0.0.1 --add-host jtlreporter_migration_1:127.0.0.1 --add-host listener:127.0.0.1 --add-host jtlreporter_listener_1:127.0.0.1 mongo:4.2.5-bionic
✔ docker.io/library/mongo:4.2.5-bionic
Trying to pull docker.io/library/mongo:4.2.5-bionic...
WARN[0033] failed, retrying in 1s ... (1/3). Error: initializing source docker://mongo:4.2.5-bionic: reading manifest 4.2.5-bionic in docker.io/library/mongo: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit 
WARN[0065] failed, retrying in 1s ... (2/3). Error: initializing source docker://mongo:4.2.5-bionic: reading manifest 4.2.5-bionic in docker.io/library/mongo: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit 
WARN[0097] failed, retrying in 1s ... (3/3). Error: initializing source docker://mongo:4.2.5-bionic: reading manifest 4.2.5-bionic in docker.io/library/mongo: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit 
Error: initializing source docker://mongo:4.2.5-bionic: reading manifest 4.2.5-bionic in docker.io/library/mongo: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

**Comment by ludeknovy** [comment]
Hello @yobshans! The timescale db image is stored in the docker hub. Based on the logs you provided, it looks like you are not able to download the images because of rate limitations - `You have reached your pull rate limit. `. See:  https://www.docker.com/increase-rate-limit

**Comment by yobshans** [comment]
Thank you for your response. I think, there is no image with docker.io/timescale/timescaledb:2.4.1-pg13 on docker hub.
Which tag I should use now? 
v3 I've installed on another machine a month ago. Now I trying to install what I cloned by git.
I would be appreciate if you can share steps to install jtl-reporter step by step flow. (separate containers commands)
Thank you

**Comment by yobshans** [comment]
Sorry I found https://hub.docker.com/layers/timescale/timescaledb/2.4.1-pg13/images/sha256-8bf64c8f8237599e3e5e7ca303c499f2e841e6a4bf7cfc6810c87a15b16ef912?context=explore

**Comment by ludeknovy** [comment]
In case you do clean install, the steps are very simple as described in https://github.com/ludeknovy/jtl-reporter#installation-steps. But not sure if docker/docker-compose is 100% compatible with podman.

Let me know if you need any further assistance from me.

**Comment by yobshans** [comment]
Just to clarify the situation. I think, you have changed data base containers between versions v3 and v4.
v3 installation which is working has podman images
REPOSITORY                                     TAG           IMAGE ID      CREATED        SIZE
localhost/novyl/jtl-reporter-db                latest        8403b3dd1ade  7 weeks ago    290 MB
docker.io/library/postgres                     11            031f4479ea79  2 months ago   290 MB
registry.access.redhat.com/ubi8/pause          latest        20b34168e325  3 months ago   3.49 MB
docker.io/novyl/jtl-reporter-fe                v3.4.6        749f9a71bd88  5 months ago   27.1 MB
docker.io/novyl/jtl-reporter-be                v3.4.2        ba60c42fabf5  9 months ago   308 MB
docker.io/novyl/jtl-reporter-listener-service  v1.0.1        a469fb4cb553  12 months ago  246 MB
docker.io/library/mongo                        4.2.5-bionic  fddee5bccba3  22 months ago  392 MB
v4 installation not working
podman images
REPOSITORY                                     TAG         IMAGE ID      CREATED       SIZE
registry.access.redhat.com/ubi8/pause          latest      7756324d098f  12 days ago   3.49 MB
docker.io/novyl/jtl-reporter-fe                v4.1.1      ef397aa072d8  2 weeks ago   27.3 MB
docker.io/novyl/jtl-reporter-be                v4.1.0      41f8959b5cbd  2 weeks ago   356 MB
docker.io/novyl/jtl-reporter-scheduler         v0.0.2      8fb4b37e6a73  4 weeks ago   230 MB
docker.io/novyl/jtl-reporter-listener-service  v2.0.1      303cdb6e6bdc  6 weeks ago   246 MB

So, don't need now postgres and mongodb, right?

**Comment by yobshans** [comment]
Well, I have a real issue with docker hub connection from that machine. So, downloaded on another machine, saved image to tar, copy to my machine and loaded. This stage passed.

**Comment by yobshans** [comment]
Now, failed on Error: statfs /root/jtl-reporter/data/jtl_reporter_v4: no such file or directory while run podman-compose up -d on stage: podman run --name=jtl-reporter-db -d --pod=jtlreporter ...................
Need create this directory before  data/jtl_reporter_v4.
Another issue it is:
Error: unknown shorthand flag: 'c' in -c
You should fix command argument from --healthcheck-command /bin/sh -c 'pg_isready -U postgres' to --healthcheck-command '/bin/sh -c pg_isready -U postgres'
Otherwise it failed
Thank you

**Comment by yobshans** [comment]
Finally, I successfully installed. Thank you for support and excellent tool.

**Comment by ludeknovy** [comment]
Glad you made it work for you!

Feel free to share your thoughts about the application with me either via discussion here or email: ludek@jtlreporter.site
