### ISSUE TITLE
The failure message is missing.

### ISSUE THREAD

**Issue by pargev** [ludeknovy/jtl-reporter#127]
**Describe the bug**
I use locust and the jtl_listener_service. When there is a failure I see only the status code. The failure message is missing.

**Configuration**
from commons.jtl_listener_service import JtlListener

@events.init.add_listener
def on_locust_init(environment, **_kwargs):
    scenario_name = os.environ.get("JTL_SCENARIO_NAME")
    project_name = os.environ.get("JTL_PROJECT_NAME")
    JtlListener(env=environment,
                project_name=project_name,
                scenario_name=scenario_name,
                backend_url=os.environ.get("JTL_BACKEND_URL"))

**To Reproduce**
Open the item page and click on the Health label

**Expected behavior**
It would be better to show failure messages as well at the bottom of the status codes chart

**Screenshots**
![image](https://user-images.githubusercontent.com/5520288/153396768-78770aff-7478-4de0-8ab2-31c07769558e.png)

**Additional context**
In logs I see only this error but I'm not sure is it related to this error or not.

be_1         | {"level":"error","message":"Processing of item 9c51adcb-5f92-4733-b13b-c88088602db1 failed Error: Error while processing dataId: 9c51adcb-5f92-4733-b13b-c88088602db1 for item: 9c51adcb-5f92-4733-b13b-c88088602db1, error: QueryResultError {\n    code: queryResultErrorCode.noData\n    message: \"No data returned from the query.\"\n    received: 0\n    query: {\"text\":\"\\n    SELECT \\n      samples.label,\\n      count(*)::int as total_samples,\\n      AVG(samples.elapsed)::real as avg_response,\\n      MIN(samples.elapsed)::real as min_response,\\n      MAX(samples.elapsed)::real as max_response,\\n      percentile_cont(0.99) within group (order by (samples.elapsed))::real as n99,\\n      percentile_cont(0.95) within group (order by (samples.elapsed))::real as n95,\\n      percentile_cont(0.90) within group (order by (samples.elapsed))::real as n90,\\n      MAX(samples.timestamp) as end,\\n      MIN(samples.timestamp) as start,\\n      count(*) filter (where samples.success = false)::int as number_of_failed,\\n      SUM(samples.sent_bytes)::bigint as bytes_sent_total,\\n      SUM(samples.bytes)::bigint as bytes_received_total\\n    FROM jtl.samples as samples\\n    WHERE item_id = $1\\n    GROUP BY samples.label;\",\"values\":[\"9c51adcb-5f92-4733-b13b-c88088602db1\"]}\n}"}

**Comment by ludeknovy** [comment]
Hi @pargev! Yes, it's missing because the https://github.com/ludeknovy/jtl-reporter-listener-service does not accept its as of now. I will adjust it, so the failure message gets accepted.

**Comment by ludeknovy** [comment]
Hi @pargev I extended the listener and it should accept failure message now. Check: novyl/jtl-reporter-listener-service:latest

https://github.com/ludeknovy/jtl-reporter-listener-service/blob/v2.0.3/openapi/openApi.yml#L89

**Comment by pargevghazaryan** [comment]
hi @ludeknovy . Thanks for the update.
I've updated the listener version from the docker-compose file and restarted. 
Now, this error throws and a report does not appear in the web UI.



`{"level":30,"time":1644566004820,"pid":18,"hostname":"3a05332c5d62","reqId":7,"req":{"method":"POST","url":"/api/v2/test-run/log-samples","hostname":"10.10.24.96:6000","remoteAddress":"10.10.21.41","remotePort":62509},"msg":"incoming request"}
{"level":50,"time":1644566004828,"pid":18,"hostname":"3a05332c5d62","reqId":7,"length":136,"name":"error","severity":"ERROR","code":"42703","position":"207","file":"parse_target.c","line":"1034","routine":"checkInsertTargets","stack":"error: column \"failure_message\" of relation \"samples\" does not exist\n    at Parser.parseErrorMessage (/src/worker/node_modules/pg-protocol/dist/parser.js:278:15)\n    at Parser.handlePacket (/src/worker/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/src/worker/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/src/worker/node_modules/pg-protocol/dist/index.js:10:42)\n    at Socket.emit (events.js:315:20)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at Socket.Readable.push (internal/streams/readable.js:223:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)","type":"Error","msg":"column \"failure_message\" of relation \"samples\" does not exist"}
{"level":30,"time":1644566004829,"pid":18,"hostname":"3a05332c5d62","reqId":7,"res":{"statusCode":500},"responseTime":8.477909088134766,"msg":"request completed"}
{"level":30,"time":1644566017922,"pid":18,"hostname":"3a05332c5d62","reqId":8,"req":{"method":"POST","url":"/api/v2/test-run/log-samples","hostname":"10.10.24.96:6000","remoteAddress":"10.10.21.41","remotePort":62622},"msg":"incoming request"}
{"level":50,"time":1644566017923,"pid":18,"hostname":"3a05332c5d62","reqId":8,"stack":"TypeError: Cannot generate an INSERT from an empty array.\n    at Object.insert (/src/worker/node_modules/pg-promise/lib/helpers/methods/insert.js:100:15)\n    at Object.insert (/src/worker/node_modules/pg-promise/lib/helpers/index.js:53:27)\n    at /src/worker/dist/routes/v2/testRun/logSamples.js:51:38\n    at Generator.next (<anonymous>)\n    at /src/worker/dist/routes/v2/testRun/logSamples.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/src/worker/dist/routes/v2/testRun/logSamples.js:4:12)\n    at Object.<anonymous> (/src/worker/dist/routes/v2/testRun/logSamples.js:36:31)\n    at preHandlerCallback (/src/worker/node_modules/fastify/lib/handleRequest.js:124:28)\n    at preValidationCallback (/src/worker/node_modules/fastify/lib/handleRequest.js:107:5)","type":"Error","msg":"Cannot generate an INSERT from an empty array."}
{"level":30,"time":1644566017924,"pid":18,"hostname":"3a05332c5d62","reqId":8,"res":{"statusCode":500},"responseTime":1.4846343994140625,"msg":"request completed"}
`

**Comment by pargevghazaryan** [comment]
Thanks, @ludeknovy for your work.
