### ISSUE TITLE
No Data - There must be at least 5 records for given label

### ISSUE THREAD

**Issue by vpier** [ludeknovy/jtl-reporter#14]
First of all, amazing tool. Well done and keep it up.

My main question is why I cannot display the graph per label and get the info messate that there must be at least 5 records for given label? Is it something wrong with the tool or the way I am using it?

Thank you very much in advance.

Kind Regards,
V

**Comment by ludeknovy** [comment]
Hi @vpier, 

thanks for reaching!

No, you are not using it wrong;), it is intentional. My reasoning for that was like I did not provide me much value if I compared only two or three items. But looking at it back, it might be too restrictive. What do you suggest regarding this functionality?

**Comment by ludeknovy** [comment]
@vpier changing the limit to 2 records.
