### ISSUE TITLE
Display additional Test Report Top Statistics Bar values 

### ISSUE THREAD

**Issue by MoritzSalein** [ludeknovy/jtl-reporter#141]
In the top of the Test Report Statistic Bar it will be nice to add some summary information from the test run.
Following information should added:
- Total Requests (count)
- Failed Requests (count)
- Recieved Bytes
- Sent Bytes
- Total Error Rate (%)

Is it possible to add these additional values? Perhaps it could be configurable in the project settings.

**Comment by ludeknovy** [comment]
Hi @MoritzSalein, yes that should be possible. Total Error Rate is already there. Not sure if error count is currently exposed in the API - will need to investigate that.

**Comment by ludeknovy** [comment]
The request count is in the header already. Does it make sense to duplicate it?

![Screenshot 2022-02-17 at 15 31 50](https://user-images.githubusercontent.com/13610612/154503013-0a59601d-8b1c-4ed3-975f-9e5517788170.png)

**Comment by MoritzSalein** [comment]
> The request count is in the header already. Does it make sense to duplicate it?
> 
> ![Screenshot 2022-02-17 at 15 31 50](https://user-images.githubusercontent.com/13610612/154503013-0a59601d-8b1c-4ed3-975f-9e5517788170.png)

Sorry, total Request is on the page and that's ok.

**Comment by ludeknovy** [comment]
Done.
