### ISSUE TITLE
Add column "Name" in Test run table on Scenation page

### ISSUE THREAD

**Issue by yobshans** [ludeknovy/jtl-reporter#144]
The new item added to test run item "name' but it is still not appeared in Test run table on Scenario page.
The current workaround upload test run the identical "name" and "note"

**Comment by ludeknovy** [comment]
Hi @yobshans, its there already. Available in "latest" tag for now.


<img width="1434" alt="Screenshot 2022-02-22 at 19 23 12" src="https://user-images.githubusercontent.com/13610612/155195123-d57f9aa1-67ea-412d-88ba-ba49a00635d9.png">
