### ISSUE TITLE
Allow to download Request Statistics table as excel/image

### ISSUE THREAD

**Issue by yobshans** [ludeknovy/jtl-reporter#146]
Hi, 
Will be very useful to allow downloading of Request Statistics table as excel tables and/or image.

Thank you

**Comment by ludeknovy** [comment]
Hi @yobshans. Would pdf do it as well? A long time ago I had the idea of adding a possibility to export a report in to a pdf file: https://github.com/ludeknovy/jtl-reporter/issues/30

**Comment by yobshans** [comment]
Hi @ludeknovy.

PDF you cannot attach to any email/doc report.  
Excel table will be better and/or image.

Thank you

**Comment by ludeknovy** [comment]
Implemented.
