### ISSUE TITLE
Some graph tooltip values and request statistic values are not rounded and sometimes wrong (v.4.2.1)

### ISSUE THREAD

**Issue by MoritzSalein** [ludeknovy/jtl-reporter#150]
In some graph tooltip (Label Chart - Network) I get unrounded values for network mbps. The same is in the target system statistic table.
And I think the values are wrong, because the legend is different to the value (see it on the first screenshot).

![2022-02-25 10_43_29-JtlReporter](https://user-images.githubusercontent.com/83296020/155693985-11a9f7f9-e0b1-4b8e-b6f0-354aa37a357c.png)

![2022-02-25 10_46_46-JtlReporter](https://user-images.githubusercontent.com/83296020/155693959-6c55368c-be0a-484d-ac9e-3cb5d5077457.png)

![2022-02-25 10_48_09-JtlReporter](https://user-images.githubusercontent.com/83296020/155693562-b492b647-a1ef-4222-86c7-aaaa0f90479c.png)
![2022-02-25 10_49_14-JtlReporter](https://user-images.githubusercontent.com/83296020/155693671-3a5b4a35-ec60-46b5-8948-c3865cecb8e3.png)

**Comment by ludeknovy** [comment]
1) Target system statistics decimals were already fixed. Once you upgrade it to a newer version it should be ok.
2) I will prepare a fix for the rounding in chart tooltips.
3) Sorry, I don't see the issue in the screenshot. Could you elaborate it a bit more please?

**Comment by MoritzSalein** [comment]
> 1. Target system statistics decimals were already fixed. Once you upgrade to a newer version it should be ok.
> 2. I will prepare a fix for the rounding in chart tooltips.
> 3. Sorry, I don't see the issue in the screenshot. Could you elaborate it a bit more, please?

To Point 3: The attached screenshot should show the problematic places. I will first try your new version and then report other places where I found possible unrounded values.

**Comment by ludeknovy** [comment]
Hi, the #1 was fixed as well, see attached screenshot.

<img width="2278" alt="Screenshot 2022-03-25 at 10 55 15" src="https://user-images.githubusercontent.com/13610612/160098329-1f9a0a6f-42c2-433c-960f-ab922748ccee.png">

**Comment by MoritzSalein** [comment]
It looks good.
