### ISSUE TITLE
Custom chart unnecessary labels (v.4.2.1)

### ISSUE THREAD

**Issue by MoritzSalein** [ludeknovy/jtl-reporter#151]
In the custom charts it shows unnecessary labels without scale, if I filtered only other values.
![2022-02-25 10_53_23-JtlReporter](https://user-images.githubusercontent.com/83296020/155694772-512f9e57-47cb-466c-9fb1-4c949f81494a.png)

**Comment by ludeknovy** [comment]
Fixed.

![Screenshot 2022-03-11 at 8 56 24](https://user-images.githubusercontent.com/13610612/157826031-f9a88ac1-f34e-4e17-831e-3e4aa9b6beb1.png)

**Comment by MoritzSalein** [comment]
Is the text "http://localhost:4200/" in the legend of your screen shot a debug output?

**Comment by ludeknovy** [comment]
Yes, that's just my testing data.

**Comment by MoritzSalein** [comment]
All right.
