### ISSUE TITLE
Save the selected chart

### ISSUE THREAD

**Issue by MoritzSalein** [ludeknovy/jtl-reporter#155]
Is it possible to save the selected values of the detail request statistic graphs and use the same selection to a different request?
Anlternatively is it possible to set in a configuration, what values I want activate in the detail request statistic graphs?

**Comment by ludeknovy** [comment]
If I understood your questions correctly, you can achieve the desired behaviour using the "Analyze chart" tab in the report, where you can create a custom chart and save it.

Do I get it right, that you would like to have a possibility to set up what labels and metrics to load in every report within a scenario?

**Comment by MoritzSalein** [comment]
I don't want to set the vaule each time I open a new chart, especially the charts with the details of a request.

I have not even thought of the "analysis chart" at all. But I see the same problem there. Whenever I leave the test run and open another run, I have to add the metrics again. The selection should be able to be preset.

**Comment by ludeknovy** [comment]
I like the idea of pre-setting the label chart. 

Just to be sure, we are talking about this chart, right?

<img width="1454" alt="Screenshot 2022-03-04 at 15 01 20" src="https://user-images.githubusercontent.com/13610612/156776868-fe3e7eab-e5cf-48c8-be9e-5bb5ad51efd8.png">

**Comment by MoritzSalein** [comment]
Yes, this chart.

**Comment by ludeknovy** [comment]
Implemented. Available in "latest". You need to upgrade FE, BE and migration.
