### ISSUE TITLE
Show always the label in the detail metrics 

### ISSUE THREAD

**Issue by MoritzSalein** [ludeknovy/jtl-reporter#156]
Is it possible to show all labels of the shown graphs in the detail metrics view? I make a screen manipulation where you can see what I mean.
![2022-03-03 16_12_35-JtlReporter](https://user-images.githubusercontent.com/83296020/156594957-c764787f-14a2-48f0-9b40-b0fe6aad83db.png)

**Comment by ludeknovy** [comment]
Hi! Do you mean to show the trends for all labels in one chart? If so, technically its not difficult, but not sure how to make the chart look and not make it cluttered.

**Comment by MoritzSalein** [comment]
I think the problem with the current style is, that it is to difficut to identify, which value has a bar chart. 

Different ideas from me:
1. Add horizontal lines at some prominent values. Then it is easier for my eye to identify the value of a bar chart.
2. Add at the bottom or right side a little table with the values of the shown bar charts. I know a similar representation from Grafana.

Back to your idea. I'm not sure, if it is good to show the actual values in an own tab. But it is already a first possibility to represent my wish.

**Comment by ludeknovy** [comment]
Ahh, now I got it. It should be possible to display the values in the column or above it/below it.

**Comment by ludeknovy** [comment]
@MoritzSalein  ?
<img width="1457" alt="Screenshot 2022-03-04 at 15 47 57" src="https://user-images.githubusercontent.com/13610612/156784532-69908dfa-360e-4456-b334-9baee63b08de.png">

**Comment by MoritzSalein** [comment]
Ok, that looks good. Could you set it up to show and hide?

**Comment by ludeknovy** [comment]
Sure!

![Uploading Screenshot 2022-03-05 at 17.01.28.png…]()

**Comment by ludeknovy** [comment]
Done
