### ISSUE TITLE
Request Statistics downloaded XLXS table is differ from we see on UI

### ISSUE THREAD

**Issue by yobshans** [ludeknovy/jtl-reporter#158]
Hi there.

I compared downloaded Request Statistics table and UI Request Statistics table and can confirm they are  different.
Downloaded:
<google-sheets-html-origin><style type="text/css"></style>

label | p90 | p95 | p99 | connect | latency | samples | errorRate | throughput | bytesPerSecond | avgResponseTime | maxResponseTime | minResponseTime | bytesSentPerSecond
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
01.OCM.Login | 7482.8 | 8341.2 | 10270.6 | 77.82 | 0 | 293 | 1.02 | 0.01 | 252.8 | 5776 | 13286 | 2981 | 189.25

UI
<google-sheets-html-origin><style type="text/css"></style>

label | samples | avg [ms] | min [ms] | max [ms] | P90 [ms] | P95 [ms] | P99 [ms] | requests/s | mbps | error rate
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
01.OCM.Login | 293 | 5,776 | 2,981 | 13,286 | 7,482.80 | 8,341.20 | 10,270.60 | 0.01 | 0 | 1.02

I think, they should be identical.

jtl-reporter-be:v4.3.0
jtl-reporter-listener-service:v2.0.4
jtl-reporter-scheduler:v0.0.2
jtl-reporter-fe:v4.3.0

Thank you

**Comment by ludeknovy** [comment]
Hi @yobshans . You want to have the column order and column headers the same way as in the UI?

**Comment by yobshans** [comment]
Hi @ludeknovy 
Yes, that will great. 

Thank you

**Comment by ludeknovy** [comment]
![Screenshot 2022-03-08 at 9 46 57](https://user-images.githubusercontent.com/13610612/157200705-66e30a5a-b34a-4477-a01d-d173bb913b34.png)

**Comment by yobshans** [comment]
Cool, thank you
