### ISSUE TITLE
Issue with volume on postgres image.

### ISSUE THREAD

**Issue by ipacbalaj** [ludeknovy/jtl-reporter#16]
When I am running docker-compose I get an Error: Encounter errors while bringing up the project. It is related to the postgres container. If the local path is not specifiend in docker-compose.yaml for novyl/jtl-reporter-db image everything works. I think there is a problem with the folder permissions or something simillar.
![image](https://user-images.githubusercontent.com/8572545/107531156-3bbe7900-6bc5-11eb-94b6-87843d198247.png)

**Comment by ludeknovy** [comment]
Hi @ipacbalaj , was this happening when you started the project for the first time or during upgrade?

**Comment by ipacbalaj** [comment]
Hi, it happend on first start.

**Comment by ipacbalaj** [comment]
Worth mentioning, I am running on a Windows machine

**Comment by ludeknovy** [comment]
The only thing I can do is to create a droplet in Digital Ocean and try to run it. But they only offer unix based systems. And unfortunately I dont have Windows machine at my disposal, but when I used it in a past I had constantly issues with docker. Did you try Windows Subsystem for Linux ?

**Comment by ludeknovy** [comment]
@ipacbalaj I tested it on fresh linux instance and it worked. That issue you reported must be  windows docker specific problem?

**Comment by ipacbalaj** [comment]
Yes it is windows docker specific. I tested on macos and it works there

**Comment by ludeknovy** [comment]
@ipacbalaj I am afraid I wont be able to help with this one unfortunately.
