### ISSUE TITLE
Request Statistics comparison table headers shows ms instead of %

### ISSUE THREAD

**Issue by yobshans** [ludeknovy/jtl-reporter#163]
Hi, 

Table's headers shows [ms] while we compare statistics and switch to percentage
Should be [%]
![Screenshot from 2022-03-22 19-00-50](https://user-images.githubusercontent.com/24528463/159590549-f3ef45f5-477c-4d69-a012-d3816d60219f.png)

Thank you

**Comment by ludeknovy** [comment]
Hi @yobshans!

I am aware of it, thats why it read: `The values show are in %`. But I agree it would be better to change the units in the headers.

**Comment by ludeknovy** [comment]
Done.
