### ISSUE TITLE
"failureMessage" is not defined

### ISSUE THREAD

**Issue by zhq745w** [ludeknovy/jtl-reporter#165]
https://github.com/ludeknovy/jtl-reporter/blob/main/scripts/jtl_listener.py#L163
"failureMessage" is not defined

**Comment by ludeknovy** [comment]
Hi @zhq745w, thanks for the report. I think it should have been `str(exception)` instead of `str(failureMessage)`

Do you wanna push the fix?

**Comment by zhq745w** [comment]
I checked locally, it seems ok :)

**Comment by ludeknovy** [comment]
Great, thank you for the fix!
