### ISSUE TITLE
[Locust] Not all requests in the report and incorrect start time

### ISSUE THREAD

**Issue by zhq745w** [ludeknovy/jtl-reporter#167]
When using Locust:

1. Some errors (like "read timeout...") not included in the JtlReporter. Its "response.reason" equals None (not string, this fail)
2. If we start the test, stop and start again after a few minutes, then the start time of the second run will be equal to the end of the first run.

**Comment by zhq745w** [comment]
Prepared MR https://github.com/ludeknovy/jtl-reporter/pull/168

**Comment by ludeknovy** [comment]
Hi @zhq745w ! The #168 is only fixing issue 1 right?

**Comment by zhq745w** [comment]
Hi, @ludeknovy ! The https://github.com/ludeknovy/jtl-reporter/pull/168 fixes both bugs (row 112 https://github.com/ludeknovy/jtl-reporter/pull/168/files#diff-baf3655b1b0d509a054b23feaf41cee1a7295c6c040b96981070757b05d21061R112)

**Comment by ludeknovy** [comment]
Perfect! Thanks!
