### ISSUE TITLE
test run name in label trend chart

### ISSUE THREAD

**Issue by artubieski** [ludeknovy/jtl-reporter#169]
hey @ludeknovy ,
thank you for the great tool! 

i would like to use it to see the performance trend of my application version by version. therefore in my use case i have imported one test run per app version, where the name of the test run is my app version. 

Now it would be great to visualize this test run name in the label trend chart e.g below or above the date on the x achsis. What do you think?

**Comment by ludeknovy** [comment]
Hey @artubieski !

Glad you like it.

If I understood you correctly, you would like to display the test run name in the following chart?
![Screenshot 2022-04-20 at 12 06 11](https://user-images.githubusercontent.com/13610612/164204735-ddb64dde-2591-42ab-a88d-dc7726a39e2f.png)

**Comment by artubieski** [comment]
yes, exactly! btw less important: the date is only shown on the first of the runs. is that intentional?

**Comment by ludeknovy** [comment]
Ok, to expose the info is fairly easy on API level, but have to dig a little deeper how to add it to the chart.

I think the date visibility is handled by highcharts automatically.

**Comment by ludeknovy** [comment]
The date was set to only be displayed at only every 5th column. But that should be the thing you asked for.

![Screenshot 2022-04-20 at 13 26 21](https://user-images.githubusercontent.com/13610612/164220572-797d5705-0730-40ce-be00-80c72edb0864.png)

**Comment by ludeknovy** [comment]
And it was there for a reason; in case there are more runs, it starts to look cramped, I think.

What about putting the test run name into toolbox only? @artubieski 

![Screenshot 2022-04-20 at 13 29 59](https://user-images.githubusercontent.com/13610612/164221114-f7db8303-861a-4520-8277-05e7b2a5f044.png)

**Comment by artubieski** [comment]
ok i see, the date is not so important to me and could be in the tooltip only, but the test run name i would rather like to see for all columns at once. 

if it is disturbing to see this for other users with other use cases then maybe the test run name could also be optionally hidden as with the bar values?

**Comment by ludeknovy** [comment]
Available in "latest" tags of `jtl-reporter-fe` and `jtl-reporter-be`

**Comment by artubieski** [comment]
wow, that was fast. thx a lot! :)
