### ISSUE TITLE
Cannot print a detail chart 

### ISSUE THREAD

**Issue by MoritzSalein** [ludeknovy/jtl-reporter#171]
If I want to print a detail chart, I get empty axis. The bars aren't on the screen. 
Similiar problem is a print of the detail chart in full screen. Then I get the bars outside the axis.
![image](https://user-images.githubusercontent.com/83296020/166646280-cb4455e7-cc68-4edb-bb98-bf1e2c22bd25.png)
![image](https://user-images.githubusercontent.com/83296020/166646441-4485d745-ecfa-4f30-905d-f866dc4652e2.png)

**Comment by ludeknovy** [comment]
Fixed. Thanks for the report.

![Screenshot 2022-05-06 at 8 14 06](https://user-images.githubusercontent.com/13610612/167077287-dee0d586-4bea-4fda-914c-faecb6db4d9c.png)
