### ISSUE TITLE
Missing bar for connection time in detail view

### ISSUE THREAD

**Issue by MoritzSalein** [ludeknovy/jtl-reporter#172]
Most times I miss the bar for average connection time in the detail view. Sometime I get the bar for it. In the screenshot, you will see two detail graphs for different requests in the same test run.
I can't explain it, what happend. Is it a problem of the large different between connection and responste time?
![image](https://user-images.githubusercontent.com/83296020/166658191-f29ae388-0f64-4386-b737-ae691b969988.png)
![image](https://user-images.githubusercontent.com/83296020/166658719-055a3b04-8a67-4813-a702-22d4384fa515.png)

**Comment by ludeknovy** [comment]
Hi @MoritzSalein, could you please check what data the API returns for the lable where you miss the bar?
![Screenshot 2022-05-06 at 8 25 47](https://user-images.githubusercontent.com/13610612/167078449-af0adcb6-cbad-4fce-8562-21a491e1ef20.png)

**Comment by ludeknovy** [comment]
Thanks! Now we know why the bars are not showing up. Are the zeros expected? 
I think there is an option how to display a bar even if the value is zero - is that what you would expect, @MoritzSalein ?

**Comment by MoritzSalein** [comment]
@ludeknovy I have two problems, 
1. Why I have a lot of requests without connect time? Now I understand it, it's an effect of the `Use KeepAlive` option. In my scenario are a lot of request to the same system and JMeter can use the KeepAlive in many cases. 
2. If I have zero connect time values then it would be good, to see the "0" in the empty area of the bar.

**Comment by ludeknovy** [comment]
1) Yes, that could be it, or the connection time is really that low (fast) - eg your generator sits very close to a system under test, and there is a very good connection between the two.

2) Ok, I think I could display the bar even when the value is zero, but it will look very similar to value "1".  The way it is displayed now is the default behavior of the highcharts library.

**Comment by MoritzSalein** [comment]
2. It can be accepted if a zero bar is displayed as a 1ms bar.

**Comment by ludeknovy** [comment]
Fixed.
