### ISSUE TITLE
Next release for  jtl-reporter-be 

### ISSUE THREAD

**Issue by zhq745w** [ludeknovy/jtl-reporter#173]
Please, tell me about the planned release date of the tag 4.4.2.
There are problems in the current version (4.4.1):

`[35457] ERROR: integer out of range`

`[35457] STATEMENT:
SELECT
time_bucket($1, timestamp) as time,
percentile_cont(0.90) within group (order by (samples.elapsed))::real as n90,
EXTRACT(EPOCH FROM (MAX(samples.timestamp) - MIN(samples.timestamp))) as interval,
(count(*) filter (where samples.success = false)::real / count(*)::real)::real as error_rate,
AVG(samples.elapsed)::real as avg_response,
SUM(samples.sent_bytes)::int as bytes_sent_total,
SUM(samples.bytes)::int as bytes_received_total,
MAX(samples.all_threads)::int as threads,
COUNT(*)::int as total
FROM jtl.samples as samples
WHERE item_id = $2
GROUP BY time;`

But i see that you have fixed it in the latest commits (in master-branch). I'm so excited for next release :)

Have a good day!

**Comment by ludeknovy** [comment]
Hi @zhq745w I am away from my laptop now. Give me like a week or so.

**Comment by ludeknovy** [comment]
Hi @zhq745w the version 4.4.3 was just released.
