### ISSUE TITLE
jtl-reporter not usable on a server with not internet access (due to missing all.css)

### ISSUE THREAD

**Issue by hideintheclouds** [ludeknovy/jtl-reporter#177]
**Describe the bug**
When used on a server that does not have access to Internet, the Dashboard and the jtl Reporter does not work properly.
This is due to the fact that the all.css resource is not embedded into the html, but rather the tool tries to download it from the Internet.

As a result of that, a lot of the buttons (i.e. deleting, comparing, etc.) are not visible.

**To Reproduce**
docker run on a server with no Internet connection

**Expected behavior**
The all.css should be embedded in the HTML to have it working also offline.
This should result in a new docker image for the web/fe component that could be then used.

Alternatively, if that is not possible, could the web/fe dockerfile read a list of additional (css) resources from environment variables, or from an entrypoint script?

**Comment by ludeknovy** [comment]
Hi @hideintheclouds, I bet the `all.css` is the font awesome icons. I will have a look at how to bundle them and avoid downloading them from the internet.

**Comment by ludeknovy** [comment]
@hideintheclouds try the `latest` tag of FE.
