### ISSUE TITLE
ERROR:  period must be greater than 0

### ISSUE THREAD

**Issue by thikoen** [ludeknovy/jtl-reporter#182]
**Describe the bug**
When uploading a csv file from JMeter the DB  throws this error:

2022-08-08 09:54:22.646 UTC [3927] ERROR:  period must be greater than 0
2022-08-08 09:54:22.646 UTC [3927] STATEMENT:
            SELECT
              time_bucket($1, timestamp) as time,
              samples.label,
              percentile_cont(0.99) within group (order by (samples.elapsed))::real as n99,
              percentile_cont(0.95) within group (order by (samples.elapsed))::real as n95,
              percentile_cont(0.90) within group (order by (samples.elapsed))::real as n90,
              MIN(samples.elapsed)::real as min_response,
              MAX(samples.elapsed)::real as max_response,
              EXTRACT(EPOCH FROM (MAX(samples.timestamp) - MIN(samples.timestamp))) as interval,
              (count(*) filter (where samples.success = false)::real / count(*)::real)::real as error_rate,
              AVG(samples.elapsed)::real as avg_response,
              SUM(samples.sent_bytes)::bigint as bytes_sent_total,
              SUM(samples.bytes)::bigint as bytes_received_total,
              COUNT(*)::bigint as total
            FROM jtl.samples as samples
            WHERE item_id = $2
            GROUP BY time, samples.label;

Log from BE:

{"level":"info","message":"Parsed 1 records in 0.006 seconds"}
error: period must be greater than 0
    at Parser.parseErrorMessage (/src/be/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/src/be/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/src/be/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/src/be/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
      length: 98,
      severity: 'ERROR',
      code: '22023',
      detail: undefined,
      hint: undefined,
      position: undefined,
      internalPosition: undefined,
      internalQuery: undefined,
      where: undefined,
      schema: undefined,
      table: undefined,
      column: undefined,
      dataType: undefined,
      constraint: undefined,
      file: 'time_bucket.c',
      line: '171',
      routine: 'ts_timestamp_bucket'
    }

**To Reproduce**
I deployed your application on Azure AKS and also build a helm chart for a kubernetes deployment. I can provide it to you for free if you would like to add it to the deployment files.
Containers are up and running and the UI works as expected, also the API does work fine. I can create user, etc. and it gets stored in the DB as expected. Only when uploading a csv file i retrieve this error. I uploaded this file:

timeStamp,elapsed,label,responseCode,responseMessage,threadName,dataType,success,failureMessage,bytes,sentBytes,grpThreads,allThreads,URL,Latency,Hostname,IdleTime,Connect
1659951524124,303,Get Info,200,OK,Users 1-1,text,true,,2116,189,1,1,https://<host>,302,jmeter-b79578bdd-z6mvz,0,222

I do not really know what the problem is here, maybe you got an idea.

**Expected behavior**
Uploading a csv as written in the docs.

**Did JtlReporter make you happay in any way?**
Yes very good app as far as i saw. Would like to stay in contact and support.

**Comment by ludeknovy** [comment]
Hello @thikoen ! Sorry for the inconvenience.
I think this issue was already solved, see: https://github.com/ludeknovy/jtl-reporter/discussions/176

It happens only in case when very short csv files are uploaded.

If you upgrade the "be" and "migration" services to [v4.4.4](https://github.com/ludeknovy/jtl-reporter-be/releases/tag/v4.4.4) this should be gone I hope.

I should also create a new release with this fix.

**Comment by thikoen** [comment]
Hi @ludeknovy  thank you very much for the quick reaction! I upgraded the images and it seem to work now :-) Are you interested in a Helm-Chart for a Kubernetes deployment? I can upload it to my GitHub when everything is ready..

**Comment by ludeknovy** [comment]
Cool! Glad it worked for you after all. 

Sure, share it if you can - I am sure this could be re-used by someone else!
