### ISSUE TITLE
Scenario Trends shows first 15 test runs instead of last

### ISSUE THREAD

**Issue by yobshans** [ludeknovy/jtl-reporter#193]
**Describe the bug**
I have about 30 test runs 
Scenario Trends shows first 15 test runs instead of last
Started from 10. 2. 2022 until 26. 4. 2022
while we have more new runs such as 20. 11. 2022 

**To Reproduce**
Add more than 15 test runs and observe the Scenario Trends

**Expected behavior**
Scenario Trends should show last 15 test runs

** Screenshots
![image](https://user-images.githubusercontent.com/24528463/203185691-f5c520c9-efc1-4c15-b86e-43c6c27701c4.png)
![image](https://user-images.githubusercontent.com/24528463/203185720-6ccbf88e-d0cc-456c-b5e9-817a8c1735a7.png)

Versions:
5a90e2f43bdd  localhost/jtlreporter_db:latest                       postgres              7 months ago  Up 4 months ago  0.0.0.0:2020->80/tcp, 0.0.0.0:5000->5000/tcp, 0.0.0.0:6000->6000/tcp  jtl-reporter-db
5d3677a0fbab  docker.io/novyl/jtl-reporter-be:v4.4.0                npm run start         7 months ago  Up 4 months ago  0.0.0.0:2020->80/tcp, 0.0.0.0:5000->5000/tcp, 0.0.0.0:6000->6000/tcp  jtlreporter_be_1
fb2d97c87c36  docker.io/novyl/jtl-reporter-listener-service:v2.0.4  npm run start         7 months ago  Up 4 months ago  0.0.0.0:2020->80/tcp, 0.0.0.0:5000->5000/tcp, 0.0.0.0:6000->6000/tcp  jtlreporter_listener_1
cb5ac066fbee  docker.io/novyl/jtl-reporter-scheduler:v0.0.2         npm run start         7 months ago  Up 4 months ago  0.0.0.0:2020->80/tcp, 0.0.0.0:5000->5000/tcp, 0.0.0.0:6000->6000/tcp  jtlreporter_scheduler_1
7ef2587d4a67  docker.io/novyl/jtl-reporter-fe:v4.4.0                nginx -g daemon o...  7 months ago  Up 4 months ago  0.0.0.0:2020->80/tcp, 0.0.0.0:5000->5000/tcp, 0.0.0.0:6000->6000/tcp  jtlreporter_fe_1

**Comment by ludeknovy** [comment]
For some reason, the order by clause is wrong, but it was correct in v3 - not sure why it got changed :|

https://github.com/ludeknovy/jtl-reporter-be/blob/f5369301f051ae4b1e2c26e09c0f9b680b3e1cb2/src/server/queries/scenario.ts#L63
