### ISSUE TITLE
Add possibility to configure Request Statistics columns

### ISSUE THREAD

**Issue by yobshans** [ludeknovy/jtl-reporter#194]
**Is your feature request related to a problem? Please describe.**
Add possibility to configure Request Statistics columns 

Now it is not configurable 
label | samples | avg [ms] | min [ms] | max [ms] | P90 [ms] | P95 [ms] | P99 [ms] | requests/s | mbps | error rate |  

Will be nice to have a possibility to configure user needed columns
For example if I'm interesting only in 90 % line I would like to see
label | samples | avg [ms] | min [ms] | max [ms] | P90 [ms] | 
And download those table as csv or image

Thank you

**Comment by ludeknovy** [comment]
Hi @yobshans 
I like the idea - the current layout will be default though and also default for anonymous users (when a report is shared).

**Comment by yobshans** [comment]
Nice, thank you

**Comment by ludeknovy** [comment]
@yobshans shall this be defined globally or per project/scenario ?
From my point of view, it should be defined on scenario or project level.

**Comment by yobshans** [comment]
I agree with you. Should be define on scenario level.
Like Thresholds or Label Filter Settings

**Comment by ludeknovy** [comment]
I have it ready (yet tests need to be updated) - implemented like this - the settings are per project and per user. But now I realized that the top metrics setting is not per user and only per scenario :/, that feels weird.

**Comment by ludeknovy** [comment]
Merged

**Comment by yobshans** [comment]
Great. Thank you
