### ISSUE TITLE
Dashboard doesn't publish start time for Recent Test Runs

### ISSUE THREAD

**Issue by yobshans** [ludeknovy/jtl-reporter#195]
**Describe the bug**
Dashboard doesn't publish start time for Recent Test Runs

**Screenshots**

![image](https://user-images.githubusercontent.com/24528463/203428519-8dbd7566-0976-4365-9a11-7e5f4faf6688.png)

**Comment by ludeknovy** [comment]
Hey @yobshans 
I cannot reproduce this issue: could you please have a look what `/api/projects/latest-items` endpoint is returning for one of the items? The returned object should contain:
```
overview: { startDate: "date"}
```

**Comment by yobshans** [comment]
Looks OK
 {
    "id": "e01dd771-0bcb-43ff-a9e4-1eacbf34ab78",
    "name": "Multi-Node-Full-ISO",
    "environment": "Staging",
    "projectName": "AI-Staging",
    "overview": {
      "maxVu": 90,
      "endDate": "2022-11-21T17:09:35.305Z",
      "duration": 757.32,
      "errorRate": 0.1,
      "percentil": 270,
      "startDate": "2022-11-21T04:32:16.118Z",
      "avgConnect": 64.53,
      "avgLatency": 163.86,
      "errorCount": 96,
      "throughput": 2.15,
      "bytesPerSecond": 13227.2,
      "avgResponseTime": 28031,
      "bytesSentPerSecond": 41293.35
    },
    "status": "0",
    "zeroErrorToleranceEnabled": false,
    "thresholdPassed": null
  },

**Comment by ludeknovy** [comment]
Does the issue still prevail? Is there anything in the browsers' console?

**Comment by yobshans** [comment]
it is OK after browser refreshing.
I'm closing issue. 
Thanks a lot
