### ISSUE TITLE
Unable to push data from Locust script running on Jenkins

### ISSUE THREAD

**Issue by abhishek813** [ludeknovy/jtl-reporter#196]
**Describe the bug**
I have a locust script running in distributed mode via Jenkins. I have configured JTLReporter in the on_locust_init method just as described in the example. I also have the JTLReporter deployed and its UI accessible. I have created a new project and a scenario via the UI. I have specified their name in the configuration. When the test is run I see the following error on Jenkins
`# first error
[2022-11-30 12:22:40,807] ip-172-23-12-97/INFO/root: Starting async item in Reporter
[2022-11-30 12:22:40,817] ip-172-23-12-97/ERROR/root: Starting async item in Reporter failed
[2022-11-30 12:22:40,817] ip-172-23-12-97/ERROR/root: Error while starting the test`

while trying to diagnose this error i looked at the logs generated by the JTL backend and noticed the below error.
{"level":"error","message":"Creating new async item failed error: null value in column \"scenario_id\" of relation \"items\" violates not-null constraint"}

I have enabled the create scenario if it doesn't exist option too.

**Expected behaviour**
Data shows up on JTLReporter

**Comment by ludeknovy** [comment]
Hey @abhishek813 !

> I have enabled the create scenario if it doesn't exist option too.

Yeah, I forgot ti add it for this endpoint. Needs to be added, gonna create a new issue for it.

I will try to replicate the issue, and get back to you.

**Comment by abhishek813** [comment]
the scenario exists. I'll retry. I am curious though, what should i provide in `backend_url` just the IP of the IP and 2020 port of the backend server?
