### ISSUE TITLE
Allow scenarios to be created programatically

### ISSUE THREAD

**Issue by abhishek813** [ludeknovy/jtl-reporter#197]
**Is your feature request related to a problem? Please describe.**
Currently, I am using API to push the test data to the dashboard. I am creating the project but i am not able to create the scenarios so this breaks the auto-magic flow that I am going for.

**Describe the solution you'd like**
Use the /projects/{project-name}/scenarios POST call to create the scenario if it doesn't exist. This should happen without enabling the create scenario flag from the UI.

**Additional context**
N/A

**Comment by ludeknovy** [comment]
Hi @abhishek813 .

It works like this:

```
## Create Scenario
curl -X "POST" "http://localhost:5050/api/projects/test/scenarios" \
     -H 'x-access-token: <token>' \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "scenarioName": "test-scenario"
}'
```

Please not that the token is the one generated in the administration, starting with `at-`
