### ISSUE TITLE
The token created using the /api/auth/login-with-token endpoint is not valid when used in other endpoints

### ISSUE THREAD

**Issue by abhishek813** [ludeknovy/jtl-reporter#198]
**Describe the bug**
I am using the /projects POST call to programmatically create projects is they don't exist. I was using the /api/auth/login-with-token endpoint to generate the JWT token and use that in the /projects call. I kept getting token is invalid error. 
I switched to using the /api/auth/login endpoint to generate the token and this was accepted by subsequent calls 

**To Reproduce**
Steps to reproduce the behaviour:
generate token using the /api/auth/login-with-token endpoint and make a POST call to /projects endpoint

**Expected behaviour**
project should be created

**Screenshots**

**Additional context**
You can get the logs by running: `docker logs <service_name>`

**Did JtlReporter make you happy in any way?**
Answering this question is not required, but if you have anything positive to share, please do so here.

**Comment by ludeknovy** [comment]
Hi @abhishek813 
The `/api/auth/login-with-token ` is supposed to be used only for authentication to interact with other services.

You can call everything within jtl-reporter-be service only using the api token.

Sorry, this is not well explained in the documentation.

**Comment by abhishek813** [comment]
When you say other services do you mean making calls to /projects endpoint? That's what I tried, right?
I tried to use the API token from the UI that too returned a similar token error.

What is the correct workflow for API?

**Comment by ludeknovy** [comment]
By the other services I mean, for example, https://github.com/ludeknovy/jtl-reporter-listener-service


Everything within here: https://github.com/ludeknovy/jtl-reporter-be/tree/master/src/server/routes
should be callable with the api token.

**Comment by ludeknovy** [comment]
If you want to create a project by API, you can do it like this:

```
## Create Project
curl -X "POST" "http://localhost:5050/api/projects" \
     -H 'x-access-token: <token>' \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "projectName": "test-project"
}'
```
