### ISSUE TITLE
How to send test result status ?

### ISSUE THREAD

**Issue by dE1l** [ludeknovy/jtl-reporter#201]
How to send test result status from jtl_listener_service ?

https://github.com/ludeknovy/jtl-reporter/blob/main/scripts/jtl_listener_service.py

<img width="1820" alt="Снимок экрана 2023-01-31 в 11 42 14" src="https://user-images.githubusercontent.com/8767620/215711182-d671d449-13f7-4229-87a7-e0fe23fb87bc.png">

**Comment by ludeknovy** [comment]
Hi @dE1l ! I think that's not currently possible. But should not be difficult to add it.

**Comment by ludeknovy** [comment]
Hi @dE1l , No, new endpoint is not needed.

https://github.com/ludeknovy/jtl-reporter-be/blob/master/src/server/controllers/item/stop-item-async-controller.ts
This controller needs to be adjusted to save the status from the request if provided.

**Comment by ludeknovy** [comment]
You can now set the status by sending "status" in the body, eg:

```
requests.post(
                f"{self.be_url}/api/projects/{self.project_name}/scenarios/{self.scenario_name}/items/{self.item_id}/stop-async",
                headers=headers, json={"status": "1"})
```


The available status values:
https://github.com/ludeknovy/jtl-reporter-be/blob/25cd74cfdba552fd9c6c13fa18d50cc4881c201a/src/server/queries/items.model.ts#L7
