### ISSUE TITLE
Initialization fails - Create new user - unexpected error

### ISSUE THREAD

**Issue by snoerenberg** [ludeknovy/jtl-reporter#206]
**Describe the bug**
After cloning the current version and running docker-compose the initialization is not possible.

the jtl-reporter-db logs have an error with each try:
```
2023-03-24 14:33:16 2023-03-24 13:33:16.528 UTC [135] ERROR:  column "role" of relation "users" does not exist at character 43
2023-03-24 14:33:16 2023-03-24 13:33:16.528 UTC [135] STATEMENT:  INSERT INTO jtl.users(username, password, role) VALUES($1, $2, $3) RETURNING id
```

**To Reproduce**
Start docker-compose and try to setup user

**Expected behavior**
User should be able to be created

**Screenshots**
![grafik](https://user-images.githubusercontent.com/4847454/227536163-0c5ccbbe-526f-484d-a7a8-1437c42000a6.png)
![grafik](https://user-images.githubusercontent.com/4847454/227536302-8198c347-c714-4ce4-a453-47e03578021a.png)

**Did JtlReporter make you happay in any way?**
Not yet :)

**Comment by ludeknovy** [comment]
Hi @snoerenberg. It takes some time to run all the migrations, you better wait for a while before creating the user.

**Comment by snoerenberg** [comment]
Thanks a lot
