### ISSUE TITLE
Add to test run item object new fields which contains link to Grafana Dashboards

### ISSUE THREAD

**Issue by yobshans** [ludeknovy/jtl-reporter#209]
Hi, 

I would like to save in scenario test run item links to Grafana Dashboard of application resource monitoring during the test. Current filed "Note" has limitation in length. 
Will be nice to have a several new fields in scenario object to use it like a links to Grafana Dashboards (or any other resources).
The single JTL reporter scenario test run will contain all required information to share with co-workers.

Thank you

**Comment by ludeknovy** [comment]
Hi @yobshans !
Do you want that new field in a report or in a scenario? I am a bit confused with your description:)

Having it per report, you could construct the link with time range parameters, so it would open the dashboard focused on the given time range covering the test duration.

**Comment by yobshans** [comment]
HI, Here is an  example what I use to create report 
curl -X POST 'http://<URL>/api/projects/<My_Project>/scenarios/<My_Scenario>/items' \
  -H 'x-access-token: <token>' \
  -F 'kpi=@"<path_to_jtl>/result.jtl"' \
  -F 'environment="MyEnv"' \
  -F 'name="<NameOfTestRun>"' \
  **-F 'note="<Version_Date_or_any_other_info>' \**
  -F 'status="0"'

Would be nice to have new field, for example -> 
 -F 'external_link="<URL_To_Grafana_Dashboard>"'

And it will be visible on Report main page 

Or, you have already any solution ?

Thank you

**Comment by yobshans** [comment]
I wanted to be able to add link here
![image](https://user-images.githubusercontent.com/24528463/230227262-93ca1f9f-edef-409d-a5b9-d7beff0b51be.png)

**Comment by ludeknovy** [comment]
Ok, no problem, I will add it.

**Comment by ludeknovy** [comment]
@yobshans is 350 characters long enough for this field?

**Comment by ludeknovy** [comment]
🔜 

<
<img width="1370" alt="Screenshot 2023-04-07 at 9 35 48" src="https://user-images.githubusercontent.com/13610612/230564452-3812509e-4ffa-4e48-847f-0cbb29679af1.png">
img width="493" alt="Screenshot 2023-04-07 at 9 36 50" src="https://user-images.githubusercontent.com/13610612/230564449-89d3339d-c45a-4472-aad8-9043c3cc027b.png">
<img width="492" alt="Screenshot 2023-04-07 at 9 35 55" src="https://user-images.githubusercontent.com/13610612/230564450-1fb0236f-7e6e-43ae-94fe-9b7c8eaed6c1.png">

**Comment by yobshans** [comment]
Hi @ludeknovy . 

Looks great. That was I missed.
One place with all related information.

/lgtm

Thanks a lot.
Yuri

**Comment by cmyllis** [comment]
@ludeknovy It is not mentioned here: https://jtlreporter.site/docs/guides/api-data-upload
Can the link be added via the api?
I tried like this and it and it didnt work.
```
external_link = $externalLink
note       = $buildNumber
```

**Comment by yobshans** [comment]
Hi, it should be 
    -F 'note="{{ jtl_note }}"'
    -F 'resourcesLink="{{ grafana_test_pods_url }}"'

**Comment by cmyllis** [comment]
Ah thanks! Though it was external_link as mentioned in your proposed older post.

**Comment by cmyllis** [comment]
https://github.com/ludeknovy/jtl-reporter-docs/pull/54
