### ISSUE TITLE
Add ability to filter test results list (/scenario/items) by environment

### ISSUE THREAD

**Issue by slash-zero** [ludeknovy/jtl-reporter#211]
**Is your feature request related to a problem? Please describe.**
Add ability to filter test results list (/scenario/items) by environment.  

**Describe the solution you'd like**
Add an option via a text field or pulldown or additional API endpoint parameter to select from the existing environments for the specific test scenario.  That way the graph showing the average response times can be compared for a single environment only, or all environments if none was specfiied.

**Comment by ludeknovy** [comment]
Hi, I like the idea of adding a filter for the scenario view, although it includes at least two endpoints - one for the listing and the other for the charts(scenario trends). And most likely new endpoint is going to be needed for the list of environments.

**Comment by ludeknovy** [comment]
👀 
https://user-images.githubusercontent.com/13610612/235139742-b67a3c6f-918e-4d9e-875c-aae2c259b87a.mov

**Comment by slash-zero** [comment]
That looks great to me! When do you expect to merge it in to main?

**Comment by ludeknovy** [comment]
I need to add some tests, but around next week.

**Comment by slash-zero** [comment]
Hi @ludeknovy,

Finally got around to upgrading to 4.8.5 today. Just wanted to thank again for adding this environment filter!

**Comment by ludeknovy** [comment]
Hi @slash-zero You're welcome. Feel free to share another improvement idea you might have.
