### ISSUE TITLE
The token you provided is invalid

### ISSUE THREAD

**Issue by tuyenlq** [ludeknovy/jtl-reporter#235]
Hi ,

I upload CSV via API but failed and received a message

`{
    "message": "The token you provided is invalid"
}`

i created API key follow the instruction - https://jtlreporter.site/docs/guides/administration/api-token and and upload file via API in postman - https://jtlreporter.site/docs/guides/api-data-upload.
Tried to get the token in web it work :).

thanks for your support

![image](https://github.com/ludeknovy/jtl-reporter/assets/10045154/fbd03b1c-f6b4-4352-bd4f-f3ef8112bcc7)
![image](https://github.com/ludeknovy/jtl-reporter/assets/10045154/9171833a-2e0e-4fc9-82dd-09ad697876c7)

**Comment by ludeknovy** [comment]
Hi @tuyenlq, did you use the token generated here https://jtlreporter.site/docs/guides/administration/api-token or the one returned from `/api/auth/login-with-token` ? Because the latter (JWT) token wont work in this case, it serves as auth token for listener-service.

**Comment by tuyenlq** [comment]
Hi @ludeknovy.

Looks like I followed the instructions wrong, i used token return from `/api/auth/login-with-token` :) to be exact is to use token generated in https://jtlreporter.site/docs/guides/administration/api-token

Thank you so much!
