### ISSUE TITLE
Load Test Result Metrics Displayed as "Trend"  graphs

### ISSUE THREAD

**Issue by kamal2222ahmed** [ludeknovy/jtl-reporter#24]
**Is your feature request related to a problem? Please describe.**
Here is a scenaario: Running Load Tests using JMeter for 11 teams, multiple times a month, need to be able to provide the Customer a sense of "Trend" over time, to get an idea of improvement ( or not ) on a continuous basis.

**Describe the solution you'd like**
A possible solution could be to gather a SET of metrics e.g.:

1. % of OK responses ( Per Test Run )
2. % of KO Responses
3. Time and Date of Test
4. Number of Threads
5. Average Latency
6. Average: Average Elapsed Time in milliseconds
7. Minimum Elapsed Time
8. Maximum Elapsed Time
9. Percentage of errors (errors / (errors + samples) * 100)
10. Number of samples per second
11. Throughput in KiloBytes/sec
12. Number of Threads Started, and Number of Threads Finished
13. Elapsed Time per Active Threads, to see how the elapsed time degrades when load increases
14. Number of errors: how many errors occured
15. % in errors: percentage of requests in error
16. % in all samples: Percentage of errors compared to total number of samples.

**Additional context**
Perhaps at a later stage of development/enhancement, we can incorporate PerfMon to superimpose the CPU and Memory graph, with the above graphs, so we can perform root cause analysis.
Since PerfMon is only for Virtual Machines, we can use cAdvisor for Containers.

**Comment by ludeknovy** [comment]
Hi @kamal2222ahmed.

If you load a scenario detail you get 90%P, throughput and error rate metrics and number of threads for each of them.
If I get you right, thats the place where they could be. There are different options how to display them:
1) Do the area customizable/interactive, but there is limit for 3 charts so they are readable
2) Display them in some kind of carousel-like way - so a user will be able to navigate through them
3) Create a new page/modal that would display some kind of performance report with some of the above-mentioned charts for the given scenario.

What do you think?

**Comment by kamal2222ahmed** [comment]
here is an example when I load a jtf file to BlazeMeter:
![image](https://user-images.githubusercontent.com/426822/112154038-456ecf80-8bba-11eb-8c69-4ad7674a341c.png)

**Comment by kamal2222ahmed** [comment]
BlazeMeter timeline report:
![image](https://user-images.githubusercontent.com/426822/112154204-6afbd900-8bba-11eb-93a6-578f5ffe6abb.png)

**Comment by kamal2222ahmed** [comment]
and ... error report:
![image](https://user-images.githubusercontent.com/426822/112154375-98e11d80-8bba-11eb-9857-aad2bf1115a5.png)

**Comment by ludeknovy** [comment]
@kamal2222ahmed the provided screenshots of BlazeMeter are from the individual performance report, right? But you asked for: `need to be able to provide the Customer a sense of "Trend" over time, to get an idea of improvement ( or not ) on a continuous basis.`

I am a bit lost now in whats the desired state from your point of view:)

**Comment by kamal2222ahmed** [comment]
@ludeknovy I apologize for the confusion. Consider the BlazeMeter reports as "look and feel" examples , as for aggregation and "Trend". Here is an example:
![image](https://user-images.githubusercontent.com/426822/112398917-8b6f8480-8cdb-11eb-8a8f-892085d73b56.png)

or:
![image](https://user-images.githubusercontent.com/426822/112399080-f325cf80-8cdb-11eb-8e96-1b266bb13558.png)
but with more than 2 comparisons. ( Configurable number of comparisons ) as there might be a limit after which it gets muddy.

with a 
![image](https://user-images.githubusercontent.com/426822/112399319-6a5b6380-8cdc-11eb-9660-82cec6725318.png) option ( apologize for adding this randomly )

**Comment by ludeknovy** [comment]
@kamal2222ahmed  here it is how it could look like
![Snímek obrazovky 2021-04-01 v 13 19 10](https://user-images.githubusercontent.com/13610612/113286889-14df1200-92ed-11eb-89dd-42bef68675ab.png)

**Comment by ludeknovy** [comment]
Implemented "basic" version of it - with current metrics available. Closing this one, but feel free to ask for additional metrics and further enhancements.
