### ISSUE TITLE
Sharing of Scenario Trends graph

### ISSUE THREAD

**Issue by ludeknovy** [ludeknovy/jtl-reporter#241]
### Discussed in https://github.com/ludeknovy/jtl-reporter/discussions/240

<div type='discussions-op-text'>

<sup>Originally posted by **johnqa** October  3, 2023</sup>
Hi, 

It's great to be able to share reports but it would be wonderful if we could also share Scenario Trends graph for a quick overview in time of how our AUT performs.

Thanks,
John</div>

**Comment by ludeknovy** [comment]
Merged.

^^ @johnqa

**Comment by johnqa** [comment]
Great, do you want me to test it? Or you will create a new release and version?

**Comment by ludeknovy** [comment]
It's available in `latest` images.
I will create a new version later.
