### ISSUE TITLE
While creating a scenario using API, is there way to have the retention as part of post request

### ISSUE THREAD

**Issue by VikasKrishnamraju** [ludeknovy/jtl-reporter#248]
While creating a new scenario through rest api is it possible to have the retention as part of the request.
This is just helps when there are more scenarios keep on adding in a project retention setting wont be a manual effort

<img width="1004" alt="image" src="https://github.com/ludeknovy/jtl-reporter/assets/24792711/4aa431d6-b60d-4a80-9ed1-2baac1ca9ad9">

**Comment by ludeknovy** [comment]
Hi @VikasKrishnamraju definitely not possible now, but should be doable.

**Comment by VikasKrishnamraju** [comment]
sure, thanks for quick comment !!!
