### ISSUE TITLE
While changing the value of "Test runs retention" for any scenario it throws an error

### ISSUE THREAD

**Issue by VikasKrishnamraju** [ludeknovy/jtl-reporter#252]
**Describe the bug**
While changing the value of "Test runs retention" for any scenario it throws an error

**To Reproduce**
Navigate to any scenario change the run retention value and the application throws an error and the value is not changed

**Expected behavior**
It should update to the desired retention value

**Screenshots**

https://github.com/ludeknovy/jtl-reporter/assets/24792711/ab7800ad-6e69-4058-8b0e-0f05ea009b88

<img width="1636" alt="image" src="https://github.com/ludeknovy/jtl-reporter/assets/24792711/0c42c46d-7610-47d9-86c4-0ada32bfbc12">

**Did JtlReporter make you happay in any way?**
yes been using the jtl reporter for a while and gives more precise info from the jtl file itself

**Comment by ludeknovy** [comment]
Hi @VikasKrishnamraju ! 
Thanks for the report. Gonna fix it.

**Comment by ludeknovy** [comment]
Fixed.

**Comment by VikasKrishnamraju** [comment]
Thanks for the quick fix @ludeknovy. Can i know when the new release would be pushed out

**Comment by ludeknovy** [comment]
the images were pushed (4.9.1), but havent created the updated docker-compose yet

**Comment by ludeknovy** [comment]
https://github.com/ludeknovy/jtl-reporter/releases/tag/v4.9.1

**Comment by VikasKrishnamraju** [comment]
Thank you @ludeknovy 👍
