### ISSUE TITLE
How is the number virtual users calculated for distributed jmeter runs?

### ISSUE THREAD

**Issue by ehmkah** [ludeknovy/jtl-reporter#255]
When I configure a jmeter tests which has a Concurrency Thread group with "target Concurrency" of 20 and I run it with distributed jmeter on two slave-hosts. Then I have a jtl file on the master which has the results of both slaves in one file. This file has a column which is named "threadName" so its possible to distingush between where the test have been run. If I import this file into jtl-reporter it says that there were 20 virtual users but i expect that it should be 40 virtual users.

How is that number calculated? 

PS: By the way. Jtl-reporter was really easy to configure and run locally and the generated statistics are beautiful. Nice work!

**Comment by ludeknovy** [comment]
Hi @ehmkah Dis you see the note related to distributed mode here https://jtlreporter.site/docs/integrations/jmeter#1-generating-and-uploading-jtl-file. ?

**Comment by ehmkah** [comment]
Thanks for your hint. Its working now :-)
