### ISSUE TITLE
Unexpected error occured whilst setting scenario retention

### ISSUE THREAD

**Issue by kierangirvan** [ludeknovy/jtl-reporter#256]
**Describe the bug**
When I attempt to set the retention period of a given scenario to a value, and click save, I get the following error:
![image](https://github.com/ludeknovy/jtl-reporter/assets/1891193/2382a2e3-7fdc-413a-8435-134bacad77de)

When I review the be container logs, I see the following being thrown:
`{"data":null,"isBoom":true,"isServer":false,"level":"error","output":{"headers":{},"payload":{"error":"Bad Request","message":"\"p50\" must be a boolean","statusCode":400},"statusCode":400}}`

**To Reproduce**
In jtlreporter fe, open project, select project settings, change "keep tests" from forever to 30 days.
![image](https://github.com/ludeknovy/jtl-reporter/assets/1891193/03152a34-0b51-4602-b128-52cf7de487ec)

**Expected behavior**
Test runs older than 30 days are deleted.

**Comment by ludeknovy** [comment]
Hi @kierangirvan . I think this issue was resolved in the latest version of the app.
See https://github.com/ludeknovy/jtl-reporter/issues/252

**Comment by kierangirvan** [comment]
Thanks @ludeknovy 

We'll get this upgraded today and confirm if this resolves the issue.  Happy if you want to close this ticket as a duplicate.
