### ISSUE TITLE
Unable to start JTL Reporter

### ISSUE THREAD

**Issue by gelsalgado** [ludeknovy/jtl-reporter#261]
I am unable to start JTL reporter. I tried running different release versions but no luck. I am getting an error when trying to access the FE. 

The error I see on the logs after trying to access the FE:
BE
![image](https://github.com/ludeknovy/jtl-reporter/assets/28947736/e3c7955a-21f6-4c2d-bec0-73fd8a1bb209)

Checking the containers, the DB does not seem to be running. 
DB
![image](https://github.com/ludeknovy/jtl-reporter/assets/28947736/392af904-ad1c-41ff-aaf1-9691453a55e4)

PS
![image](https://github.com/ludeknovy/jtl-reporter/assets/28947736/4d8c3a08-adf7-4911-aff1-7d1d43156037)

**Comment by ludeknovy** [comment]
Hi @gelsalgado !
I've quickly checked the logs, and I can see that the DB is shutting down due to lack of resources (memory) - see the fatal error Out of memory.

**Comment by gelsalgado** [comment]
Closing the issue

**Comment by ludeknovy** [comment]
Good! If you have any other feedback or questions, please feel free to contact me.
