### ISSUE TITLE
Update Status For Result File

### ISSUE THREAD

**Issue by thepeanutgalleryandco** [ludeknovy/jtl-reporter#262]
**Is your feature request related to a problem? Please describe.**
It is currently only possible to set the status for a Result file when uploading it for the first time. We are not able to edit the entry and mark the status as something different after investigating the results within the dashboard.

**Describe the solution you'd like**
As a user, I should be able to edit an entry and change the status of the result set based on my investigation of the results.

**Additional context**
N/A

**Comment by ludeknovy** [comment]
Hello @thepeanutgalleryandco ! 
Sounds reasonable, I will extend the functionality.

**Comment by ludeknovy** [comment]
Done.
