### ISSUE TITLE
Cannot load swagger UI

### ISSUE THREAD

**Issue by puran157** [ludeknovy/jtl-reporter#264]
**Describe the bug**
Swagger UI page doesn't load when launched from API-Docs link.

**To Reproduce**
Go to user -> API Docs:

**Expected behavior**
Swagger UI should load.

**Screenshots**

**Additional context**
You can get the logs by running: `docker logs <service_name>`

**Did JtlReporter make you happay in any way?**
Answering this question is not required, but if you have anything positive to share, please do so here.

Cause:- Jtl reporter is deployed over http using docker, the swagger UI tries to load css and js using https after initial request

**Comment by ludeknovy** [comment]
Hi @puran157 
Yes, sorry, it's not working, and even if it was, it's unfortunately outdated. I forgot to remove the link.
I know it's less user friendly, but you can check all the API from here: https://github.com/ludeknovy/jtl-reporter-be/tree/master/src/server/routes
