### ISSUE TITLE
Support for Mac Silicon - docker-compose returning platform error on scheduler

### ISSUE THREAD

**Issue by yyahav** [ludeknovy/jtl-reporter#265]
**Is your feature request related to a problem? Please describe.**
Running `docker-compose up -d` on a Mac Silicon (e.g. Macbook Pro M1) results in the following error:
```
scheduler The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s[+] Running 7/9
```

**Describe the solution you'd like**
Please add support for linux/arm64/v8 platform for running the compose on Mac Silicon machines.

**Comment by yyahav** [comment]
The issue was the I ran it straight after cloning.
Looking for a newer version on docker hub I noticed scheduler alredy has an arm64 version - 0.0.5, I updated the compose yml and it works.
Thank you!

**Comment by ludeknovy** [comment]
Thanks for letting me know. I've fixed the scheduler version number.
