### ISSUE TITLE
Large file (2.2 GB) gets stuck when trying to upload

### ISSUE THREAD

**Issue by jorgetamayo21** [ludeknovy/jtl-reporter#269]
**Describe the bug**
I am using the integration with Locust and at the end of a 2 hour and 30 minute test it started uploading but stalled. The file weighs 2.2 GB and I have not found a way to upload it, in the Web UI it was stuck as "item in progress"

**To Reproduce**
Run a test that generates a 2.2 GB result file

**Expected behavior**
That the file uploads without problems and can be viewed in reporter

**Screenshots**
![imagen](https://github.com/ludeknovy/jtl-reporter/assets/59964898/13d1d0b5-8abf-4279-b78b-2867c2038006)

**Additional context**
upload log at the end of the Locust test
uploading
{"itemId":"33118836-eb29-47fd-a51c-6bdd7893dd79"}
uploading
{"itemId":"3517c50d-9f1d-4138-ae53-f790199becf3"}

**Comment by jorgetamayo21** [comment]
For about 40 minutes it was processing then the jtl-reporter page crashed, I restarted the machine and it raised the page but the item is still stuck at "item in progress"

I will implement that continuous upload method better, but I will still report the problem to see if I can rescue the results of my test

**Comment by ludeknovy** [comment]
The stale item can be changed only directly in the DB for now.

The only mechanism I can think of to delete the failed processing is to set a time threshold (eg: 4 or 8 hours) after which the item would be declared as failed and its status would get changed.

**Comment by ludeknovy** [comment]
Also, this seems to be the same problem as https://github.com/ludeknovy/jtl-reporter/issues/259

**Comment by ludeknovy** [comment]
> The problem occurred because the machine had only 8 GB of memory and jtl-reporter at the time of processing the file exceeded those 8 GB.

Was it processing more files at once during that time? The 8GB of RAM should be enough to process one 2.2 GB file. As mentioned, I made some changes to the part of streaming the file into the DB. 

Do you think you could remove any sensitive information from your file and share it with me? I don't have such a big file at my disposal, and I would like to perform more tests and see if there's still a problem I could fix with memory management.

**Comment by jorgetamayo21** [comment]
Give me your email and I'll send you the file

**Comment by ludeknovy** [comment]
Closing this issue, the further steps can be followed here: https://github.com/ludeknovy/jtl-reporter/issues/259
