### ISSUE TITLE
Remove stale/failed test runs

### ISSUE THREAD

**Issue by ludeknovy** [ludeknovy/jtl-reporter#271]
**Is your feature request related to a problem? Please describe.**
In case test processing fails (eg the whole application crashes), the test run status stays "in progress" for ever.

**Describe the solution you'd like**
Use the scheduler service to pick up test runs that are in progress for a long time(8hrs) and remove them and all the related sample data.

**Comment by ludeknovy** [comment]
@jorgetamayo21
you can try out the newest version of the scheduler, which will delete stale reports older than 8 hours.

Just in case, create a backup of your database: https://jtlreporter.site/docs/guides/backup-and-restore-database

novyl/jtl-reporter-scheduler:v0.0.6

**Comment by jorgetamayo21** [comment]
It works perfect

![imagen](https://github.com/ludeknovy/jtl-reporter/assets/59964898/4af5934f-5dbf-4fc5-a133-9f76e6961a4a)

![imagen](https://github.com/ludeknovy/jtl-reporter/assets/59964898/e0a65a52-bd63-4a7d-ab16-81474db93c3a)
