### ISSUE TITLE
Status feature in continuous upload results

### ISSUE THREAD

**Issue by jorgetamayo21** [ludeknovy/jtl-reporter#276]
I'm trying to migrate from my Locust implementation that generates the JTL file and then uploads it, to the continuous results upload implementation and I can't find the "status" feature that is in the JTL file implementation:

![imagen](https://github.com/ludeknovy/jtl-reporter/assets/59964898/1b8d68fa-18a2-4580-bb5c-38f96e8bcb30)

I am tying that feature to a custom "getStatus" method but in the implementation of continuous upload of results I don't see it anywhere. The status is none and I don't see a way to set it when the test ends.

![imagen](https://github.com/ludeknovy/jtl-reporter/assets/59964898/37206af2-b00e-412b-8885-dd832ba4f5c9)

![imagen](https://github.com/ludeknovy/jtl-reporter/assets/59964898/dcba2464-a83a-4d62-b6f7-000450fba90e)

**Comment by ludeknovy** [comment]
Hi @jorgetamayo21 !
You can send the status in the body: https://github.com/ludeknovy/jtl-reporter-be/blob/742f0d6457ee08e36bc17c63fd4af9c5fd4cd73e/src/server/schema-validator/item-schema.ts#L73

The accepted values: https://github.com/ludeknovy/jtl-reporter-be/blob/742f0d6457ee08e36bc17c63fd4af9c5fd4cd73e/src/server/schema-validator/item-schema.ts#L18
