### ISSUE TITLE
Continuous results uploading don't record the total of the performance test carried out

### ISSUE THREAD

**Issue by jorgetamayo21** [ludeknovy/jtl-reporter#281]
**Describe the bug**

I did two distributed performance tests with Locust.io.

I used 20 virtual machines with 16 virtual CPUs (8 cores) and 65 GB of ram, 8 locust workers by virtual machine, reaching 20 thousand threads and approximately 7300 req/s.

I used one virtual machine with 8 virtual CPUs (4 cores) and 32 GB of ram for JTL-Reporter

Test results are sent in real time to both Grafana (from locust-plugins) and JTL-Reporter using the "Continuous results uploading" method.

The first test was saved fine and the start and end of the test match what was recorded by Grafana.

JTL-Reporter:
![imagen](https://github.com/ludeknovy/jtl-reporter/assets/59964898/f696ef85-b643-42ee-b5b6-d4f428f6feef)
Grafana:
![imagen](https://github.com/ludeknovy/jtl-reporter/assets/59964898/05586c1e-769c-4f65-9526-b17d2ddb4cf0)

However, in the second test JTL-reporter tells me that it finished at 08:03 while in Grafana I have results until 08:14

JTL-Reporter:
![imagen](https://github.com/ludeknovy/jtl-reporter/assets/59964898/a28c1543-94ef-418f-827c-3cd9fc4906ec)
Grafana
![imagen](https://github.com/ludeknovy/jtl-reporter/assets/59964898/903019a5-952f-4257-80a5-32f4de473a18)

**Expected behavior**
Let JTL-Reporter record the total of the performance test carried out

Thank you very much in advance, beautiful tool, we are very happy using it.

**Comment by ludeknovy** [comment]
Hi @jorgetamayo21 
Please check this method: https://github.com/ludeknovy/jtl-reporter/blob/921f314b5038a107971596d6a7fd4e10669cb23f/scripts/jtl_listener_service.py#L178

And also check the logs of the run when some of the samples were not reported. My guess is, that it got terminated before all the samples were uploaded to the listener service.

**Comment by jorgetamayo21** [comment]
Indeed, 5103684 uploaded samples were recorded in the log.

![imagen](https://github.com/ludeknovy/jtl-reporter/assets/59964898/916904dc-4d72-4e29-b126-d2ebff8003b6)

**Comment by ludeknovy** [comment]
Alright. Maybe try to remove the timeouts from the `join` https://www.gevent.org/api/gevent.greenlet.html#gevent.Greenlet.join in theory it should wait for the background task to finish

**Comment by ludeknovy** [comment]
Also, be sure that the DB and listener service have enough resources to handle the load.

**Comment by jorgetamayo21** [comment]
Leave all without timeout.

![imagen](https://github.com/ludeknovy/jtl-reporter/assets/59964898/81bc2e92-40b0-4937-90da-bbee837b2b91)

Additionally, I doubled the resources of the VM for JTL-Reporter, leaving it with 16 virtual CPUs (8 cores) and 64 GB of ram.

Tomorrow we will do the same test and I will tell you if it worked to close the issue. Thank you so much!

**Comment by jorgetamayo21** [comment]
I just finished a test of more than 3 hours, 17 thousand threads, generating approximately 53 million requests.

This showed me the log when I stopped the test

![imagen](https://github.com/ludeknovy/jtl-reporter/assets/59964898/199a7a5e-614b-4656-b3be-46c0190d69bf)

52 minutes have passed already and it still appears as processing

![imagen](https://github.com/ludeknovy/jtl-reporter/assets/59964898/64bbcbf1-cc1b-475a-bc2f-d84640d26a47)

The cpu of the "master" machine is at 10%, I suppose even sending the data to jtl-reporter

![Captura desde 2024-05-24 09-30-48](https://github.com/ludeknovy/jtl-reporter/assets/59964898/3112ee59-5a2a-4055-9c7e-bad9d88a1cb0)

I will continue to report on all this, I am missing a "progress" indicator in sending the data

**Comment by jorgetamayo21** [comment]
Just finished sending to jtl-reporter!

![imagen](https://github.com/ludeknovy/jtl-reporter/assets/59964898/1e448439-f554-4524-a425-82fdfacda279)

jtl-reporter keeps showing me "processing"

![imagen](https://github.com/ludeknovy/jtl-reporter/assets/59964898/29b1993a-32ac-4d48-9ad0-0b2ebaec28cd)

jtl-reporter VM instance is still working

![imagen](https://github.com/ludeknovy/jtl-reporter/assets/59964898/6439142f-deb9-42d3-be57-914d580ba420)

**Comment by jorgetamayo21** [comment]
The jtl-reporter VM instance seems to have stopped working, there is not much CPU movement and the occupied memory dropped sharply :(
![imagen](https://github.com/ludeknovy/jtl-reporter/assets/59964898/3fa50040-beed-4e6a-9c8d-14b7a036de72)

**Comment by ludeknovy** [comment]
Hi @jorgetamayo21 
Thanks for the detailed report. 
Would you care to share the edited python script for uploading the samples to the app using multiple gevent to make it faster?


Yes, please try again with v4.10.2 ? Hopefully the memory issue should be fixed in v4.10.2.

**Comment by jorgetamayo21** [comment]
I made the pull request so you can look at it in detail.

https://github.com/ludeknovy/jtl-reporter/compare/main...jorgetamayo21:jtl-reporter:new_jtl_listener_service_script

**Comment by ludeknovy** [comment]
Thanks @jorgetamayo21
