### ISSUE TITLE
Select the summarized percentile of the report

### ISSUE THREAD

**Issue by golfzaptw** [ludeknovy/jtl-reporter#284]
Currently, when going to the detail of the report, It will show 90 percentiles in the header. Is it possible to change it to 95 percentiles or 99 percentiles?

**Comment by ludeknovy** [comment]
Hi @golfzaptw . Currently, that's not possible. Only P90 is supported.

**Comment by golfzaptw** [comment]
@ludeknovy Is there a roadmap for this feature? or should I fix it myself in jtl-reporter-be?

**Comment by ludeknovy** [comment]
It has never been requested before, so no plans for it. But I guess there is one now :D

If you would like to contribute, please feel free do so, but remember to also adjust jtl-reporter-fe.

**Comment by golfzaptw** [comment]
got it. many thanks :D
