### ISSUE TITLE
Comparison Across Scenarios

### ISSUE THREAD

**Issue by jfucci** [ludeknovy/jtl-reporter#287]
As of now, in order to compare test runs I would have to upload all the result files I have to the same scenario.
I would like to be able to compare a test run in one scenario to a test run that exists in another scenario of the same project.
For instance, in the screenshot, I would like to have the option of comparing "config 1 - dev" with "config 2 - dev"

![image](https://github.com/ludeknovy/jtl-reporter/assets/2520208/af5e1c43-6d95-41f8-84ac-7a7790b103cd)

I envision in the "compare" modal a drop down or even just titled sections to display runs by scenario.

**Comment by ludeknovy** [comment]
Hi @jfucci. I will think about it - need to check how complex it would be.

**Comment by ludeknovy** [comment]
Implemented.
