### ISSUE TITLE
Installation Bug on docker using Docker-compose

### ISSUE THREAD

**Issue by sanjeet2u** [ludeknovy/jtl-reporter#288]
**Describe the bug**
During the installation of the application, TimescaleDB throws a permission error. 

**To Reproduce**
Step 1: Clone the Repo
Step 2: Enter in the repo parent directory
Step 3. docker-compose up

**Expected behaviour**
to install

**Screenshots**

![image](https://github.com/ludeknovy/jtl-reporter/assets/59883263/a99f6616-d14d-4704-a8a0-28807cafff5e)

**Comment by ludeknovy** [comment]
Hi @sanjeet2u 
This does not look like a jtl-reporter issue, but rather a docker issue, specifically, it depends how you have it set it up. 
Try to google for `docker permission denied for mounted volume`
