### ISSUE TITLE
Missing 90th Percentile from Stats View

### ISSUE THREAD

**Issue by kierangirvan** [ludeknovy/jtl-reporter#289]
**Describe the bug**
We have recently provisioned the JTL reporter into a new ECS deployment, running on fargate.  We have successfully uploaded a basic kpi.jtl and from the logs we can see its been successfully processed.  But the scenario trends is not showing the 90th percentile:
![image](https://github.com/ludeknovy/jtl-reporter/assets/1891193/ee5af945-71bc-42af-a786-dc0eaab4ab70)

Oddly, on the same version, launching the containers locally, it works fine with the exact same kpi.jtl:
![image](https://github.com/ludeknovy/jtl-reporter/assets/1891193/f0edfe98-8a31-4cfa-b507-e71828d22e15)

I can confirm that the scenario trends on both instances are identical i.e.
![image](https://github.com/ludeknovy/jtl-reporter/assets/1891193/49943817-a7df-41e6-a8bd-4421785d9116)

We have attempted to toggle the 90th on/off, but no joy.  This also makes the Project view of the scenarios a little odd i.e.:
![image](https://github.com/ludeknovy/jtl-reporter/assets/1891193/b2b6e737-3492-4b5a-b292-4c0fac99af3b)

When it should look like this:
![image](https://github.com/ludeknovy/jtl-reporter/assets/1891193/ed685026-779b-42ac-b2bb-34336faf6689)

**Expected behavior**
The 90th percentile should be visible on the scenario trend and project overview of all scenarios.

**Screenshots**
See above.

**Additional context**
As previously mentioned, the logs do not show anything alarming, but can share if required.
Also the version we are running is the latest i.e. v4.10.2
Obviously with this working on a local installation, it does point to an issue with how we've provisioned this in AWS, but if you could shed some light on what container would be responsible for calculating and displaying this metric that would be amazing.

**Comment by ludeknovy** [comment]
Hi @kierangirvan 
The `be` container is responsible for all the aggregations while `fe` for its representation.
Please, check if the p90 data is being returned from the BE in the developer tools in your browser.

**Comment by kierangirvan** [comment]
On my local (and working) instance, I see the following:
![image](https://github.com/ludeknovy/jtl-reporter/assets/1891193/243364d4-f764-441c-a087-6262e2c8a9ea)

Yet on the cloud hosted instance, I see the following:
![image](https://github.com/ludeknovy/jtl-reporter/assets/1891193/5e731eff-4b7d-40c0-8f6e-4c995f0ba90a)

In the FE logs I can see the 500 being returned:
![image](https://github.com/ludeknovy/jtl-reporter/assets/1891193/ecce5038-7ac0-4b19-87cf-97b485631b3f)

And in the BE, it shows the following exception:
![image](https://github.com/ludeknovy/jtl-reporter/assets/1891193/62615d29-1dc0-4e9a-9860-c197e9d1c213)

**Comment by ludeknovy** [comment]
It looks like the query for a scenario is failing, could you, please, try to run the following query in the hosted instance DB:
```
SELECT * FROM jtl.scenario
    WHERE name = $2 AND project_id = (SELECT id FROM jtl.projects WHERE project_name = $1);

```
where $2 is the scenario name, and $1 is the project name.

**Comment by kierangirvan** [comment]
Output from the cloud hosted DB:
```
                 id                  |       name        |              project_id              | threshold_enabled | threshold_error_rate | threshold_percentile | threshold_throughput | analysis_enabled | delete_samples | zero_error_tolerance_enabled | keep_test_runs_period | generate_share_token | label_filter_settings |                       label_trend_chart_settings                                                                            | extra_aggregations |                               apdex_settings                               | min_test_duration
--------------------------------------+-------------------+--------------------------------------+-------------------+----------------------+----------------------+----------------------+------------------+----------------+------------------------------+-----------------------+----------------------+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+----------------------------------------------------------------------------+-------------------
6e40e4ce-48e8-4480-aba3-dd6ac3731b55 | e2e_all_soak_test | 28162ab7-523a-474d-9a14-84669f54b051 | f                 |                    5 |                    5 |                    5 | t                | f              | f                            |                     0 | f                    | []                    | {"p90": true, "p95": true, "p99": true, "errorRate": true, "avgLatency": false, "throughput": false, "virtualUsers": true, "avgResponseTime": false, "avgConnectionTime": false} | f                  | {"enabled": false, "satisfyingThreshold": 100, "toleratingThreshold": 400} |                 5
```

And this is from my local instance, the name of the scenario is different but thats expected:
```
                  id                  |         name          |              project_id              | threshold_enabled | threshold_error_rate | threshold_percentile | threshold_throughput | analysis_enabled | delete_samples | zero_error_tolerance_enabled | keep_test_runs_period | generate_share_token | label_filter_settings |                                                                            label_trend_chart_settings                                                                            | extra_aggregations |                               apdex_settings                               | min_test_duration 
--------------------------------------+-----------------------+--------------------------------------+-------------------+----------------------+----------------------+----------------------+------------------+----------------+------------------------------+-----------------------+----------------------+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+----------------------------------------------------------------------------+-------------------
 f02fba1c-933b-428f-bc33-dc5fee16bdd1 | e2e_all_peak_perf     | 2fbdce07-e3da-4ec5-aa78-53af5b913cb3 | f                 |                    5 |                    5 |                    5 | t                | f              | f                            |                     0 | f                    | []                    | {"p90": true, "p95": true, "p99": true, "errorRate": true, "avgLatency": false, "throughput": false, "virtualUsers": true, "avgResponseTime": false, "avgConnectionTime": false} | f                  | {"enabled": false, "satisfyingThreshold": 100, "toleratingThreshold": 400} |                 5
```

Output looks similar from what we can see.

We have also reinstalled the DB, now running 2.4.1-pg13, previously it was on 2.15.2-pg14 and that seems to have sorted the 500s being returned by the FE, and the error message we observed no longer is being reported.  But the 90th percentile is still not showing.

Any thoughts?

**Comment by ludeknovy** [comment]
@kierangirvan I've pushed a fix addressing this issue. Please try to pull the `latest` FE image.

**Comment by kierangirvan** [comment]
@ludeknovy pleased to confirm that pulling the latest FE worked.  We are confused why the same version was working locally, are you able to expand on what was the defect?

Really great work and thanks for your quick turnaround with this.

**Comment by ludeknovy** [comment]
Recently, I've changed the property on BE side, but the trends’ chart I forgot to update, while the other parts were updated and working fine.

So your local version processed the data before that change in processing, so it was still using the old property, thus working fine.

**Comment by ludeknovy** [comment]
> @ludeknovy pleased to confirm that pulling the latest FE has fixed the scenario view of the 90th percentile. However, on the project view (where it shows a trend over each scenario), this is still blank for the 90th: ![image](https://private-user-images.githubusercontent.com/1891193/344922273-099d803d-a543-4262-b88e-5091aa11fdc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MDYwMTUsIm5iZiI6MTcxOTkwNTcxNSwicGF0aCI6Ii8xODkxMTkzLzM0NDkyMjI3My0wOTlkODAzZC1hNTQzLTQyNjItYjg4ZS01MDkxYWExMWZkYzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDJUMDczNTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTNiMTViZjYxMzI2ZGZmOTNlMzM5NzE4Zjc3MTQ0MTkzZjIzNDAyYWRhZTg1ZTAyYmYxZjM2MmRmNDI4MTlhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.X-GNJcfvUw2Y9HEz1Z1Wy8utj0heJWzBRKsCR9CZdic)

I will fix it during today as well.

**Comment by ludeknovy** [comment]
Fixed 🤞

**Comment by kierangirvan** [comment]
We have deployed the latest FE and indeed this is now resolved.  Thanks as always @ludeknovy
