### ISSUE TITLE
Read-only users cannot access testruns of a shared scenario

### ISSUE THREAD

**Issue by jorgetamayo21** [ludeknovy/jtl-reporter#290]
**Describe the bug**
When using a Shared Scenario link, the readonly user is able to see the shared scenario but when clicking on a test, the test does not open.

**To Reproduce**
1) Create a link to share a Scenario
2) Log in with a "readonly" user
3) Enter the shared Scenario link
4) Click on a test run

**Expected behavior**
The "readonly" user is expected to be able to see the test run

**Screenshots**
![imagen](https://github.com/ludeknovy/jtl-reporter/assets/59964898/a42824d7-bbea-4369-8781-43a449dae8d3)

![imagen](https://github.com/ludeknovy/jtl-reporter/assets/59964898/fa00fa15-a41e-458f-b8f4-d424a062c5a7)

**Comment by ludeknovy** [comment]
Hi @jorgetamayo21 !
That's not a bug but a feature. The bug here is that the chart is clickable.

See history: https://github.com/ludeknovy/jtl-reporter/discussions/240
