### ISSUE TITLE
Deploying as Helm chart in Openshift: Permission Denied for mkdir

### ISSUE THREAD

**Issue by timothyjmtan** [ludeknovy/jtl-reporter#291]
**Describe the bug**
I am able to launch the jtl-reporter stack locally via Docker Desktop with no issues. I used `kompose` to convert the docker-compose yml file into Helm charts. The only modification I did after that was to modify the images in each file so that it correct points to the Openshift ImageStreams repository, which I have confirmed to be correct.

When I attempt to do a `helm install xxx . --namespace yyy`, I noticed that when resources such as `fe` and `be`  deploy, they run into a permissions denied issue. The other resources such as `migration` are also having issues, but they also seem to be related to permissions.

be: `Error: EACCES: permission denied, mkdir '/src/be/uploads`
fe: `nginx: [emerg] mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)`

Looks like a user permissions issue. How can I fix this?

**To Reproduce**
- Use `kompose` to convert the docker-compose yml into helm charts 
- Attempt to launch the generated files (after necessary modifications) into Openshift as a Helm release. 

**Expected behavior**
- Resources should launch without any permissions issue
- If certain permissions are required, we should be able to address this via commands in the docker-compose / Helm chart.
  
**Screenshots**

**Additional context**
You can get the logs by running: `docker logs <service_name>`

**Did JtlReporter make you happay in any way?**
Answering this question is not required, but if you have anything positive to share, please do so here.

**Comment by ludeknovy** [comment]
Hi @timothyjmtan Sorry for a late reply.

I am not sure I can help much here.  Are you sure that there's no problem on your side, the way your docker is configured/run? 

This is the very first time every anyone complaining about such a thing.
