### ISSUE TITLE
FE doesn't respond if BE is restarted

### ISSUE THREAD

**Issue by mcleodj** [ludeknovy/jtl-reporter#292]
**Describe the bug**
We are running JTL reporter on ECS, using fargate. Each container is running independently.
When the BE container restarts, the FE can sometimes not function (i.e. display a white screen on the UI) until it is restarted.

**To Reproduce**
Restart BE after all containers are up and functional.

**Expected behavior**
The FE to auto-recover from losing connection to the original BE.

**Screenshots**

**Additional context**
To work around the hardcoded `be` value in nginx.conf we are running the below command on startup.
```
  command = [
    "/bin/sh",
    "-c",
    "sed -i 's/server be/server be.jtl-reporter.local/' /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
  ]
```

**Did JtlReporter make you happay in any way?**
Answering this question is not required, but if you have anything positive to share, please do so here.

**Comment by ludeknovy** [comment]
Hi @mcleodj.
Do I understand it correctly that if you restart the BE, the FE will never reconnect to the BE again?
Is this behaviour specific for your current setup or when running it using docker-compose?

**Comment by mcleodj** [comment]
That is correct.

I don't know if this is specific to running this on ECS or not as this is the only place that I've run the app.

**Comment by ludeknovy** [comment]
I will try to reproduce it locally, but my guess it's specific to your setup, as it looks like something had changed in networking after you restarted the application.

**Comment by mcleodj** [comment]
It is actually an nginx "issue" (actually behaving by design). Nginx caches the upstream IP address until reload or restart. My options here are to either put the BE behind a load balancer with a persistent IP or to use the resolver directive in nginx.

Either way, not an application problem, thanks for looking anyway.
