### ISSUE TITLE
Comparison of resources like CPU, memory etc

### ISSUE THREAD

**Issue by puran157** [ludeknovy/jtl-reporter#293]
**Is your feature request related to a problem? Please describe.**
JTLReporter as of now compares Throughput and Latency of the calls but resources comparison is missing

**Describe the solution you'd like**
Is it possible to compare resources as well like CPU, memory in JTLReporter for each test?

**Additional context**

**Comment by ludeknovy** [comment]
Hi! Yes, that should be possible. Although not sure where and how to display it. Any ideas?

**Comment by puran157** [comment]
Sorry for delayed response @ludeknovy :).
I see that locust master/worker CPU is already captured but its displayed as isolated chart. It cannot be compared with base(or any other) run. A way to stream custom data to JTL such that JTL blindly draws chart comparison without any processing would be awesome. With this, anybody can add any service KPI (specific to service) and analyze against base-run.

**Comment by ludeknovy** [comment]
@puran157 I am not saying its not useful, but I am not sure where to display the other(compared to) chart. Because currently the resources’ chart is displayed in a modal window. So I am not sure how to design the solution properly.

**Comment by ludeknovy** [comment]
Imlemented.
