### ISSUE TITLE
Anonymous shared link to report in external notification

### ISSUE THREAD

**Issue by jorgetamayo21** [ludeknovy/jtl-reporter#296]
I added an external notification to my scenario that points to a channel in Teams to send me this little summary card. 

Could a new anonymous shared link be automatically created and added to these cards allowing the report to be viewed?

![imagen](https://github.com/user-attachments/assets/f250f573-2ea6-4c55-a90d-2f1002d8b467)

**Comment by ludeknovy** [comment]
Hi @jorgetamayo21 
Yes, this could be done, but I am not sure how to deal with the token if a new one is required or somehow re-use the current solution when generating a token for a report use.

Btw wouldn't you like to contribute to this?

**Comment by jorgetamayo21** [comment]
The idea is that jtl-reporter creates a shared link token for the report on which the notification is sent, for each notification a token and shared link

I'm not an expert in javascript but I'll try to code it.
