### ISSUE TITLE
Index Corruption During Large Import

### ISSUE THREAD

**Issue by kierangirvan** [ludeknovy/jtl-reporter#303]
**Describe the bug**
We regularly import a large jtl file post test (we've previously discussed importing/feeding the file during the test but this is not possible).  But the import seems to work just fine however, we have recently increased our load profile meaning the jtl file has jumped from 800mb to 1gb and as a result we are seeing an index corruption message in the BE logs.

`{"level":"error","message":"Error occurred during data parsing and saving into database: error: index \"_hyper_1_14_chunk_samples_item_idx\" contains unexpected zero page at block 28401, item_id: fb38060d-63a9-4703-b278-5a972734d624"}`

We have reindexes this index and tried to import again and it fails with the same error message.

**To Reproduce**
Try and import a large (>1gb) jtl file 

**Expected behavior**
The jtl file to successfully upload.

**Screenshots**
<img width="1676" alt="Screenshot 2024-10-29 at 17 02 28" src="https://github.com/user-attachments/assets/48180a37-8046-43fe-9497-c3fde72f06b4">

**Comment by ludeknovy** [comment]
Hi @kierangirvan 
what version do you run?

**Comment by kierangirvan** [comment]
Looks like v4.10
![image](https://github.com/user-attachments/assets/39e077c1-afa5-4c74-ab28-08baa65c8747)

**Comment by ludeknovy** [comment]
Thanks. My advice would be to try to upgrade to v5 as this uses a newer version of timescaledb.

But to be fair, I have no idea, whether this going to solve your problem or not :|

**Comment by kierangirvan** [comment]
We've decided to completely rebuild the service (unfortunately meaning we lose our previous tests), but this seems to have introduced a new issue:
`{"level":"error","message":"Error occurred during samples aggregation in database: Error while processing dataId: 28f5f5c9-ac17-455d-9e97-49e4f7e50530 for item: 28f5f5c9-ac17-455d-9e97-49e4f7e50530, error: error: function lttb(timestamp with time zone, integer, unknown) does not exist, item_id: 28f5f5c9-ac17-455d-9e97-49e4f7e50530"}`

**Comment by ludeknovy** [comment]
What kind of database image do you use? it looks like you are not using the one from here https://github.com/ludeknovy/jtl-reporter/blob/main/db/Dockerfile

**Comment by kierangirvan** [comment]
My cloud engineer shared the following from our AWS hosted jtl reporter, this is the same as my local install:
`postgres=# \dx
                                               List of installed extensions
    Name     | Version |   Schema   |                                     Description
-------------+---------+------------+--------------------------------------------------------------------------------------
plpgsql     | 1.0     | pg_catalog | PL/pgSQL procedural language
timescaledb | 2.14.2  | public     | Enables scalable inserts and complex queries for time-series data (Apache 2 Edition)
uuid-ossp   | 1.1     | public     | generate universally unique identifiers (UUIDs)`

**Comment by ludeknovy** [comment]
lttb function missing means, you dont have the timescale db toolkit installed.
If you use the FROM timescale/timescaledb-ha:pg16.4-ts2.16.1-all, then you dont have to do anything special as this is already preinstalled. If you've chosen different db image, you have to install it manually.

**Comment by kierangirvan** [comment]
I have fed this back to the cloud engineer, I'll let you know if this fixes the issue.

Obviously the original error in this ticket is still a concern, and we had to entirely rebuild the stack therefore losing all of our historical tests.

**Comment by ludeknovy** [comment]
But why didnt you make a backup of your data??

**Comment by kierangirvan** [comment]
We do have backups of the jtl files, so we can re-upload them.
