### ISSUE TITLE
Too many access resource and role log messages are being reported

### ISSUE THREAD

**Issue by ddennerline3** [ludeknovy/jtl-reporter#306]
**Is your feature request related to a problem? Please describe.**
The JTL reporter backend process is reporting a large number of the messages below. These log message aren't explicit enough to be useful (no resource name), so we would like to control whether resource logging is enabled.

```
{"level":"info","message":"User 9145a7db-56a0-408a-b2a1-ae249965b212 with role operator accessing a resource with allowed roles: readonly,operator,admin","timestamp":"2024-12-10 14:12:25"}
{"level":"info","message":"User 9145a7db-56a0-408a-b2a1-ae249965b212 with role operator accessing a resource within alpha project","timestamp":"2024-12-10 14:12:25"}
```
**Describe the solution you'd like**
Can these messages be downgraded to "Debug" please?
https://github.com/ludeknovy/jtl-reporter-be/blob/b3e27d25c980dad5eae1f3f6e280b9418f503763/src/server/middleware/authorization-middleware.ts#L9

**Additional context**

**Comment by ludeknovy** [comment]
Hi @ddennerline3 
Yes, its possible to change the level to debug.

**Comment by ludeknovy** [comment]
Changed: https://github.com/ludeknovy/jtl-reporter-be/commit/e91426510817dfa8bf8dcfa99353aeac43bd6d19
