### ISSUE TITLE
Problem with login

### ISSUE THREAD

**Issue by Anakinn** [ludeknovy/jtl-reporter#34]
EDIT: After 2nd attempt I was able to login.

After docker-compose can not login

1. docker-compose up -d
2. navigate to : http://IP_ADDRESS:2020
3. enter username: admin
password: 2Txnf5prDknTFYTVEXjj
Error: Something went wrong

**Expected behavior**
To be able to login.

Logs from docker:

| {"name":"error","length":108,"severity":"ERROR","code":"42P01","position":"15","file":"parse_relation.c","line":"1159","routine":"parserOpenTable","level":"error"}
be_1         | {"message":"Unexpected error: error: relation \"jtl.users\" does not exist","level":"error"}

**Comment by ludeknovy** [comment]
Hi @Anakinn If it was the very first launch it was most likely caused by unfinished migrations.
