### ISSUE TITLE
Add information on how to contribute to the project

### ISSUE THREAD

**Issue by ludeknovy** [ludeknovy/jtl-reporter#43]
**Describe the solution you'd like**
Add on how to contribute information

**Comment by kamal2222ahmed** [comment]
How to Contribute

```Code of Conduct```
we could use : https://www.contributor-covenant.org
```Semantic Versioning```
https://semver.org
```Branch Organization```
Here we can elaborate on the Tag based approach, as I did not see feature branches
```Bugs```
```How to Get in Touch```
```Pull Request```
ref: https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github
Before submitting a pull request, please make sure:
1. docker version
2. docker-compose versioon
3. platform ( Mac, Windows, Linux )
4. Fork the repository and create your branch from master.
5. Create a Branch ( git checkout -b <Branch Name>
6. Work on the Feature/Bug/Enhancement, etc
7. Test 
8. Create a Pull Request

**Comment by ludeknovy** [comment]
@kamal2222ahmed 
[code of conduct](https://github.com/ludeknovy/jtl-reporter/blob/master/CODE_OF_CONDUCT.md)
[contributing.md](https://github.com/ludeknovy/jtl-reporter/blob/master/.github/CONTRIBUTING.md)
