### ISSUE TITLE
Notification and Alerting Mechanism for jtl-reporter

### ISSUE THREAD

**Issue by kamal2222ahmed** [ludeknovy/jtl-reporter#56]
**Is your feature request related to a problem? Please describe.**
I see, eventually jtl-reporter being used as part of the Continuous Integration Pipeline, as it scales vertically as an application, it would require notification and alerting mechanism 

**Describe the solution you'd like**
This could be achieved by:
1. Integrating with an Existing CI tool, like Jenkins
2. Building an alerting and notification framework with jtl-reporter
3. Building and interface so that the API/REST API can be used by developers to integrate any CI framework

**Additional context**
For Alerting and Notification, the Authentication and Authorization, mechanisms in place would play a major role, as well as integration with Source Code Control Systems, like git, subversion and mercurial. Group Policies are also essential. 
This could open up a pandora's box, as firms are using in-house Jenkins, Cloud based  CI Solutions and AWS, GCP and Azure's built-in solutions. We can always start with the most in-demand and simple use cases, and perhaps it will get easier as more integrations are developed.

**Comment by ludeknovy** [comment]
Hi @kamal2222ahmed 
1 )could you be maybe a bit more specific on how do see the integration? Lets use Jenkins as an example. What information would like the application send to Jenkis and how could Jenkins uset it / display it?
2) The application has integration with MS TEAMS, if you set it up, you will receive incoming webhook after each report is processed. It can be extended for Slack as well. 
3) I think most of the JtlReporter's REST API can be used with token.

**Comment by ludeknovy** [comment]
@kamal2222ahmed closing it as it was not further specified what should be implemented. Feel free to re-open with additional details.
