### ISSUE TITLE
More permissive license

### ISSUE THREAD

**Issue by brandon-miles** [ludeknovy/jtl-reporter#61]
Would it be possible to use (or add) a more permissive license for this project? Either MIT or Apache 2.0? Would love to use this, but unfortunately the existing license is preventing us from doing so. Thanks!

**Comment by ludeknovy** [comment]
Hi @brandon-miles what’s the issue with GPL3 ? Thanks.

**Comment by brandon-miles** [comment]
Using GPL3 would be extremely difficult at my company. Sorry for being vague, but there are very good reasons why this is the case. I understand it's asking a lot to completely change the license, but would it be possible to maybe dual-license this with MIT or Apache 2.0?

**Comment by ludeknovy** [comment]
Hi @brandon-miles. Thanks for your response. I really have to think about it and read a bit more about the consequences. But I think I chose the current licence on purpose. Do you plan to add some customizations to the project for your specific use case?

**Comment by brandon-miles** [comment]
Yes, this project fits our use case quite well, and we'd love to contribute to it.

**Comment by ludeknovy** [comment]
Thanks. I will consider the licence change.

**Comment by ludeknovy** [comment]
@brandon-miles I think it make sense to change the licence for this repository: https://github.com/ludeknovy/jtl-reporter
as it contains the integration scripts, docker-compose, etc meant for further customization and usage. And it make no sense to make the end user to open source their modifications here.

But I will keep the GPL3 for the other parts - be, fe, listener service for now.

**Comment by brandon-miles** [comment]
@ludeknovy Great, thank you. Actually, not to be pushy, but it would make more sense for the actual components to be under a more permissive license as well since it's more likely our contributions would be made there. Would that be possible?

**Comment by ludeknovy** [comment]
@brandon-miles Maybe I miss something, but how is the GPL3 restricting you (or someone else) from contributing to the project? What GPL3 is about - if you make any changes, you cannot redistribute it without making them open sourced as well. Or am I wrong?

**Comment by brandon-miles** [comment]
Contributing to or using GPL3 projects is basically a non-starter for my company, and I'm sure many other corporations. Specifically the concern is libraries getting linked inside proprietary software, and then having to make this software open source, potentially disclosing large swaths of sensitive code.

I understand for this project our resistance doesn't quite make sense since we would be using the software and contributing back within the agreement, but unfortunately exceptions to the policy are hard to come by, and I doubt they would be granted here.

On the flip side, I think there could potentially be other companies in the same boat as us that would use this if the license were more permissive, so that could be some incentive to use MIT or Apache.

Again, I appreciate the consideration; I understand this is a really tough ask, but I think this would benefit others in the same position. Thanks!

**Comment by ludeknovy** [comment]
> `Specifically the concern is libraries getting linked inside proprietary software, and then having to make this software open source, potentially disclosing large swaths of sensitive code.

Yes, I understand that, but this project is not a library like for example jest or babel. You do not really link it to other proprietary software, right? In case you customize the app, then yes, you are supposed to make these changes open sourced as well and that was my intention from the very beginning;)

**Comment by brandon-miles** [comment]
There is no concern for linking this particular project, but some companies have a blanket policy in place to prevent this. I wish this wasn't the case, but it is. Would really love to use and contribute to this!

**Comment by ludeknovy** [comment]
@brandon-miles I understand that, but for now the project will continue under GPL licence.
