### ISSUE TITLE
Using JTL-Reporter with AWS DocumentDB

### ISSUE THREAD

**Issue by dennisconrad** [ludeknovy/jtl-reporter#68]
Tagging @kierangirvan

**Describe the bug**

Note: We are aware that this might not be an issue with jtl-reporter.

We are trying to replace mongodb with AWS DocumentDB, which (allegedly) is compatible with mongodb.  We are using the docdb 4.0.0 engine version and jtl-reporter connects successfully.

When trying to import a JMeter (Taurus) kpi.jtl file, we are receiving the following error `MongoError: Second argument to arrayElemAt must be numeric`

**To Reproduce**

We deployed a docdb 4.0.0 engine version DocumentDB, created a DB called `jtl-data` on it, and ran the following commands in that database after opening a mongo shell session:

```javascript
db.createCollection("data-chunks");
newCol = db.getCollection("data-chunks");
newCol.createIndex({ dataId: -1 }, { name: "data-id-index" })
```

That seems to all be fine so far:

```
rs0:PRIMARY> db
jtl-data
rs0:PRIMARY> show collections
data-chunks
rs0:PRIMARY> db['data-chunks'].getIndexes()
[
        {
                "v" : 4,
                "key" : {
                        "_id" : 1
                },
                "name" : "_id_",
                "ns" : "jtl-data.data-chunks"
        },
        {
                "v" : 4,
                "key" : {
                        "dataId" : -1
                },
                "name" : "data-id-index",
                "ns" : "jtl-data.data-chunks"
        }
]
```

We are also able to successfully connect to the DocumentDB from jtl-reporter via the following `MONGO_CONNECTION_STRING`:

```
mongodb://user:pass@docdb-host:27017/jtl-data?tls=true&tlsInsecure=true&retrywrites=false"
```

(Without `retrywrites=false`, importing data fails with `MongoError: Retryable writes are not supported`.)

Unfortunately, importing data fails with:

```
Starting KPI file streaming and saving to Mongo with dataId: c7df80c4-ca73-4a85-a689-522b6705f691
Error while processing item: 240af087-0bd8-4706-9138-2f5781e048ed: Error: Error while processing dataId: c7df80c4-ca73-4a85-a689-522b6705f691 for item: 240af087-0bd8-4706-9138-2f5781e048ed, error: MongoError: Second argument to arrayElemAt must be numeric
````

It *does* write data to the DocumentDB, though: 
https://gist.github.com/dennisconrad/cc0693636e928e529d369d2ddf53f2b8

According to Amazon, `arrayElemAt` is supported by DocumentDB: https://docs.aws.amazon.com/documentdb/latest/developerguide/mongo-apis.html#mongo-apis-aggregation-pipeline-array

This is the kpi.jtl file used for the test: https://gist.github.com/dennisconrad/d7e7b7e06edad05e18c6b59a47499ac8

Any help would be appreciated!

**Comment by dennisconrad** [comment]
Thanks so much for the quick reply!  So much for AWS DocumentDB compatibility with MongoDB... 

We tried working around this somehow, but DocumentDB is severely limited, and we were unsuccessful.  We are now using a persistent EFS (NFS) volume, which - with limitations - is working.

Again, thanks!

**Comment by ludeknovy** [comment]
@dennisconrad Glad you made it work in AWS.

Would you mind sharing detailed description on how to do it? I am sure there are others who could benefit from that. 

We could put it into docs: https://github.com/ludeknovy/jtl-reporter-docs
