### ISSUE TITLE
events.request_success has been depricated since Locust v1.5+

### ISSUE THREAD

**Issue by taitelman** [ludeknovy/jtl-reporter#75]
so no stats are collected in streaming in Locust.
https://github.com/ludeknovy/jtl-reporter/blob/0c679cf2ed4a5ea7ad836fea6a0acc7c6d80d6e6/scripts/jtl_listener.py#L67

need to shift the python listener to `request` eventhook. see https://docs.locust.io/en/stable/api.html#locust.event.Events.request_failure

**Comment by ludeknovy** [comment]
Hi @taitelman. I am aware of these changes, but the deprecated hooks should still work. Be sure you use the latest version of locust. There was a bug in the early 1.5 version causing it not to work properly.

**Comment by ludeknovy** [comment]
I was already working on the upgrade, but did not finish it. Will try to push it soon.

**Comment by taitelman** [comment]
I'm using Locust 1.5.3 . upload locust CSV fails in parsing. streaming fail too . I moved the code to use Request EventHook

**Comment by ludeknovy** [comment]
When you moved to request event hooks did it work for you then?

Last time I was testing it I was using v1.5.x I think.

could you please share an anonymized sample of the csv you tried to upload?

**Comment by taitelman** [comment]
I moved the code to Eventhooks after it failed. trying to fix it.
found out locust server has a `--csv-full-history` flag. will try that flag first...

**Comment by ludeknovy** [comment]
Wait, thats not what you should upload to JtlReporter! The plug-in/listener should generate new file in logs folder! And test oné should be uploaded, se the csv format: https://jtlreporter.site/docs/integrations/introduction#1-uploading-csv-file

**Comment by taitelman** [comment]
yes. I know the reporter CSV . I realized it has its own unique structure so that's why I'm fixing the eventhook file 
```
def _requestHook(self, request_type, name, response_time, response_length,response, context,exception,  **kw):
        success="false" if response.status_code > 300 else "true"
        exceptAsStr = "" if exception is None else str(exception)
        self.add_result(success, request_type, name,
                                response_time, response_length, exceptAsStr,response)
```
fixing add_result result too since kw no longer there.

**Comment by ludeknovy** [comment]
Good, I got confused for a while!

**Comment by taitelman** [comment]
still a work in progress... I have lots of TBD
```
def add_result(self, success, _request_type, name, response_time, response_length, exception, response):
        logging.info("add_result ") # , success, _request_type , name,response_time, response_length,exception)
        timestamp = int(round(time() * 1000)) #  datetime.now().timestamp() # TBD int(round(time() * 1000))
        response_message = "OK" if success == "true" else "KO"
        # check to see if the additional fields have been populated. If not, set to a default value
        status_code = response.status_code
        data_type = "TBD" # kw["data_type"] if "data_type" in kw else "unknown"
        bytes_sent = "0" # TBD len(response.request.text) # kw["bytes_sent"] if "bytes_sent" in kw else "0"
        group_threads = str(self.runner.user_count)
        all_threads = str(self.runner.user_count)
        latency = response.elapsed  # kw["latency"] if "latency" in kw else "0"
        idle_time = "0" # TBD kw["idle_time"] if "idle_time" in kw else "0"
        connect = "0"  # TBD kw["connect"] if "connect" in kw else "0"
        hostname = self._worker_id
```

**Comment by taitelman** [comment]
if it works I will make a PR

**Comment by ludeknovy** [comment]
I just tested https://github.com/ludeknovy/jtl-reporter/blob/master/scripts/jtl_listener.py with locust 1.5.3 and it works without any issues.

**Comment by taitelman** [comment]
really ? in K8s  cluster ? nothing it uploaded. in fact, the hook to _test_stop is never called when you stop the locust test.

**Comment by taitelman** [comment]
will use annotations: 
```
@events.test_stop.add_listener
    def _test_start(self, *a, **kw):
        self._create_results_log()
```

**Comment by ludeknovy** [comment]
1. Does it generate the csv for you?
2. Do you get any errors?

**Comment by taitelman** [comment]
it generates the CSV. but the event test_stop is never called. so nothing is uploaded.

**Comment by ludeknovy** [comment]
Hmm, that's weird. In my case the `_test_stop` method gets called.

**Comment by taitelman** [comment]
https://github.com/locustio/locust/issues/1778

**Comment by taitelman** [comment]
event works. it was my master worker setup.

**Comment by ludeknovy** [comment]
Glad you solved it!
