### ISSUE TITLE
Error: TypeError: can only join an iterable.

### ISSUE THREAD

**Issue by ggivler-SCALA** [ludeknovy/jtl-reporter#78]
**Describe the bug**
When running a 1 user 1 hatch-rate test, I get the following error:
[2021-06-17 11:15:29,217] scau-p0063/ERROR/root: Uncaught exception in event handler: 
Traceback (most recent call last):
  File "c:\users\ggivler\scalapythondevelopment\locustpoc\venv\lib\site-packages\locust\event.py", line 40, in fire
    handler(**kwargs)
  File "C:\Users\ggivler\ScalaPythonDevelopment\LocustPOC\jtl_listener.py", line 111, in _test_stop
    self.results_file.write(self.row_delimiter.join(
TypeError: can only join an iterable

This seems to be because, I am not running a Master/Worker script. So self.master_csv_data is not iterable.

**To Reproduce**
Ran a test with the following command line parameters: locust -f locustfile.py --logfile=20210617-111000_1_users_5m_duration_rampup_1.log --csv=20210617-111000_1_users_5m_duration_rampup_1 -u 1 -r 1 --run-time 5m --stop-timeout 300 --config=locust.conf --max_items=40000 --username administrator --password ********--offset_limit=1000

--max_items, -- username, --password, and --offset_limit are custom command line parameters.

The resulting csv file had the only the header in the file:
timeStamp,elapsed,label,responseCode,responseMessage,dataType,success,bytes,sentBytes,grpThreads,allThreads,Latency,IdleTime,Connect,Hostname

**Expected behavior**
That it not error out and produce an output file, 

**Screenshots**

**Additional context**

**Did JtlReporter make you happay in any way?**
It is very nice looking, and if it worked would save me a lot of time. I have a custom handler that creates a specific file, I may try and modify it to create the fields the JtlReporter expects and see if I can upload it and get test results. Thanks for your hard work, the docker compose created the image and started them up with no problems.

**Comment by ludeknovy** [comment]
Hi @ggivler-SCALA, yes IG you dont run it in distributed mode it most likely won’t work, as stated here: https://jtlreporter.site/docs/integrations/locust

I guess the listener could be updated to support even standalone(master only) mode. I did not support it as I don’t personally use it and find it very limiting, but not denying others might have a use case for it

**Comment by ggivler-SCALA** [comment]
Sorry, I missed that, my bad… can we change it to a enhancement request?



Greg



*From:* Ludek ***@***.***>
*Sent:* Thursday, June 17, 2021 12:52 PM
*To:* ludeknovy/jtl-reporter ***@***.***>
*Cc:* ggivler-SCALA ***@***.***>; Mention <
***@***.***>
*Subject:* Re: [ludeknovy/jtl-reporter] Error: TypeError: can only join an
iterable. (#78)



Hi @ggivler-SCALA <https://github.com/ggivler-SCALA>, yes IG you dont run
it in distributed mode it most likely won’t work, as stated here:
https://jtlreporter.site/docs/integrations/locust

I guess the listener could be updated to support even standalone(master
only) mode. I did not support it as I don’t personally use it and find it
very limiting, but not denying others might have a use case for it

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ludeknovy/jtl-reporter/issues/78#issuecomment-863401700>,
or unsubscribe

**Comment by ggivler-SCALA** [comment]
In the short term I have moved to running the tests in distributed mode.

**Comment by ludeknovy** [comment]
@ggivler-SCALA do you want to test https://github.com/ludeknovy/jtl-reporter/pull/79 ?

**Comment by ggivler-SCALA** [comment]
Everything looks good, I did a quick test with both Master Worker and
Stand-Alone mode, and both worked correctly.



Thank you,



Greg Givler





*From:* Ludek ***@***.***>
*Sent:* Friday, June 18, 2021 4:18 AM
*To:* ludeknovy/jtl-reporter ***@***.***>
*Cc:* ggivler-SCALA ***@***.***>; Mention <
***@***.***>
*Subject:* Re: [ludeknovy/jtl-reporter] Error: TypeError: can only join an
iterable. (#78)



@ggivler-SCALA <https://github.com/ggivler-SCALA> do you want to test #79
<https://github.com/ludeknovy/jtl-reporter/pull/79> ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ludeknovy/jtl-reporter/issues/78#issuecomment-863853735>,
or unsubscribe
