### ISSUE TITLE
Can jtl-reporter support large size jtl file to upload?

### ISSUE THREAD

**Issue by gocoder2020** [ludeknovy/jtl-reporter#8]
Hi  Ludek:
      Hello, firstly this tool is great!
      I want to upload one jtl file whose size is 1.2GB to jtl-reporter by using jtl-reporter api liking this: 
     `curl -v -H 'x-access-token: <my token>' -F environment=<my env> -F status=0 -F note=#<my note> -F hostname=<my host> -F kpi=@//<my path>/<my test>.jtl -F errors=@//<my path>/error.jtl http://<my jtl-reporter>:2020/api/projects/debug/scenarios/large/items`.
      The command executed successfully without any errors, but I couldn't find the data in <my jtl-reporter>.
      Can you please help to instruct me if there is something wrong with what I had done?
      Thanks a lot!

**Comment by ludeknovy** [comment]
Hi @gocoder2020

Thanks!

Here is how things work:
Server accepts the file and starts parsing them and saving to the DB and later it starts calculating the metrics.

If you could run `docker-compose logs` and upload the file again, there should appear an error message if there is any issue during either parsing, saving or calculating the data. If there is such an error, please post it here.

**Comment by gocoder2020** [comment]
Hi Ludek,

I found such error:

> {"message":"Error while processing item: d692e04d-596c-4a0e-9370-743e35de3a30: MongoError: $push used too much memory and cannot spill to disk. Memory limit: 104857600 bytes","level":"error"}

This mean the mongoDB has the 100Mb size limitation. So I just modify the mongoDB cache size? or something else need to be done in the /projects/{projectName}/scenarios/{scenarioName}/items API of JTL-Reporter?

Any suggestions are appreciated from you for me, thanks!

**Comment by ludeknovy** [comment]
Hi @gocoder2020!

I was expecting this to be the issue.

This limit should be possible to change: https://jira.mongodb.org/browse/SERVER-44174

But maybe the whole aggregation pipeline should be refactored? :/

I will look at changing the mongo settings, but it will take me some time as I need to prepare the large JTL file first.

**Comment by ludeknovy** [comment]
Or another option could be to use older version of mongoDB without this change: https://jira.mongodb.org/browse/SERVER-44174

**Comment by gocoder2020** [comment]
Hi Ludek,

Thank you for your quick reply! Our time zone should be very close:)

I tried the method in below cmd in mongodb:
`> newLimit = 2000 * 1024 * 1024;
2097152000
> db.adminCommand({setParameter: 1, internalQueryMaxAddToSetBytes: newLimit});
{ "was" : 104857600, "ok" : 1 }`

But I still got failed and found the response message in my chrome browser:
> failed	[ {…}, {…}, {…}, {…}, {…}, {…}, {…} ]
0	Object { id: "63de3dfb-14bd-43d5-b1f2-f88159039fc2", reportStatus: "error", uploadTime: "2020-10-16T03:44:57.662Z" }
id	"63de3dfb-14bd-43d5-b1f2-f88159039fc2"
reportStatus	"error"
uploadTime	"2020-10-16T03:44:57.662Z"
1	Object { id: "8dd10815-e9e6-4a24-8fee-08ba087fee70", reportStatus: "error", uploadTime: "2020-10-16T05:45:16.874Z" }
id	"8dd10815-e9e6-4a24-8fee-08ba087fee70"
reportStatus	"error"
uploadTime	"2020-10-16T05:45:16.874Z"
2	Object { id: "963543a2-a5a0-4a9a-84bd-69590645a915", reportStatus: "error", uploadTime: "2020-10-16T05:09:00.669Z" }
id	"963543a2-a5a0-4a9a-84bd-69590645a915"
reportStatus	"error"
uploadTime	"2020-10-16T05:09:00.669Z"

The mogodb version is:
`> db.version();
4.2.5`

**Comment by ludeknovy** [comment]
@gocoder2020  thanks for the try!

Could you, please, fetch the logs from docker-compose again? As there should be more specific error message.

**Comment by gocoder2020** [comment]
@ludeknovy 

How to get logs from docker-compose? Yesterday, I used the cmd `docker logs -f <Container_ID>`. But it only displayed console message. Do you want a log file? Could you tell me the method?

**Comment by ludeknovy** [comment]
@gocoder2020 

docker-compose logs shows output from all services. 

The example you provided is just from FE service. But I need it from backend service.

The best way is to share anonymized your JTL file, so I could run it agains my development environment and try to find a fix.

**Comment by gocoder2020** [comment]
@ludeknovy 

I rerun the test and got a new one result which is a little big. How could I send the JTL file to you?

**Comment by gocoder2020** [comment]
@ludeknovy 

The file was compressed to 140.9MB now. But this is seem still big for github website. How should I send it to you?

**Comment by ludeknovy** [comment]
@gocoder2020 thans a lot!

Would you mind sending it over dropbox/google disk/ or any of your preferable cloud storage and provide the link either here or via my email?

**Comment by gocoder2020** [comment]
@ludeknovy 

It's fine for me to send the JTL file via mail. Can you visite the below address? 
The shared cloud storage is here 
`URL: https://pan.baidu.com/s/1ftWSUCzgATSk2VnMlquLJg
Fetch Code: jpin`
The limited time is one week.

**Comment by ludeknovy** [comment]
@gocoder2020 

Unfortunately, the baidu service wont allow me to download it without installing some kind of software which is all in Chinese. 

I realized 140mb could be too large for email.

What about https://wetransfer.com/ ? They allow fast and easy file sharing without any registration - just click three dots icon and choose "get transfer link".

**Comment by gocoder2020** [comment]
@ludeknovy 

It's great. You can visit https://we.tl/t-yKUCVWRVZh. The file name is base-sample_202010191433.jtl.zip.
If you could not get it, just tell me.

**Comment by ludeknovy** [comment]
@gocoder2020 
Downloaded. Thanks!

**Comment by gocoder2020** [comment]
@ludeknovy 

You've been trying so hard！Admire you:)

**Comment by ludeknovy** [comment]
Hey @gocoder2020 
My bad I overlooked the command you mentioned:

> I tried the method in below cmd in mongodb:
> `> newLimit = 2000 * 1024 * 1024;
> 2097152000
> 
> > db.adminCommand({setParameter: 1, internalQueryMaxAddToSetBytes: newLimit});
> > { "was" : 104857600, "ok" : 1 }`

it should be: 

`db.adminCommand({setParameter: 1, internalQueryMaxPushBytes: newLimit});`

I used the same value as you provided `newLimit = 2000 * 1024 * 1024;`

and it works, although it is slow. To parse and save the date it takes ~24min and another 10min take all the aggregations.

I have a few ideas on how to make it slightly faster.

**Comment by gocoder2020** [comment]
Hey @ludeknovy 
I found the mogon:4.2.5-bionic in https://hub.docker.com was disappeared.
You might modify you docker-compose.yml file to reflect such fact.

If you have good resolution of upload the large JTL file, I prefered to take a try after you developed.
Hope the speed could be increased more. Thanks for your hard work!

**Comment by ludeknovy** [comment]
@gocoder2020 
mongo:4.2.5-bionic is still available in registry, its not only listed here: https://hub.docker.com/_/mongo
meaning it is not causing any issues. I might upgrade mongo to 4.4 in future, but it will require some testing.

It's on my roadmap to do so. 
https://github.com/ludeknovy/jtl-reporter-be/issues/55
https://github.com/ludeknovy/jtl-reporter-be/issues/56

Thanks for rising this issue, I will close it as soon as I update readme with possibility to increase `internalQueryMaxPushBytes `

**Comment by ludeknovy** [comment]
To avoid long times until the report is generated (uploading, saving to DB, processing), you can use new listener service https://github.com/ludeknovy/jtl-reporter-listener-service  and stream the samples during your test run.
