### ISSUE TITLE
Taking long time for processing reports

### ISSUE THREAD

**Issue by SonaliSihra** [ludeknovy/jtl-reporter#9]
Hi @ludeknovy  , i have followed this tutorial [generate-intuitive-locust-io-reports-with-jtl-reporter](https://medium.com/@novyludek/generate-intuitive-locust-io-reports-with-jtl-reporter-c40c71913d64) and in the end the csv file was created under logs folder and i have uploaded the same in jtl reporter instance. It is a very light weight file but it kept processing. The response as follows:
![image](https://user-images.githubusercontent.com/50992346/99370535-d15aad00-28e3-11eb-9a9a-29b1ca2206b7.png)
```
{
  "failed": [],
  "inprogress": [
    {
      "id": "4674e493-be7e-43d8-9bdd-d75c5a93a5aa",
      "reportStatus": "in_progress",
      "uploadTime": "2020-11-17T08:33:42.883Z"
    }
  ]
}
```
Can you please check i'm using locust version 1.3.1, python version 3.6.8
![image](https://user-images.githubusercontent.com/50992346/99370937-4fb74f00-28e4-11eb-85ec-3c28b6a2e624.png)

Found this error in jtlreporter_be_1

`{"message":"Starting new item processing for scenario: tests","level":"info"}
{"level":"info","message":"POST /api/projects/test_load/scenarios/tests/items 200 82ms","meta":{}}
{"message":"Starting KPI file streaming and saving to Mongo with dataId: e825a683-bce0-420b-84e6-be3cea054ca7","level":"info"}
(node:17) UnhandledPromiseRejectionWarning: MongoError: Topology is closed, please connect
    at processWaitQueue (/src/be/node_modules/mongodb/lib/core/sdam/topology.js:998:42)
    at NativeTopology.selectServer (/src/be/node_modules/mongodb/lib/core/sdam/topology.js:440:5)
    at selectServerForSessionSupport (/src/be/node_modules/mongodb/lib/operations/execute_operation.js:174:12)
    at executeOperation (/src/be/node_modules/mongodb/lib/operations/execute_operation.js:34:12)
    at Collection.insertOne (/src/be/node_modules/mongodb/lib/collection.js:516:10)
    at /src/be/dist/server/controllers/item/create-item-controller.js:74:38
    at Generator.next (<anonymous>)
    at /src/be/dist/server/controllers/item/create-item-controller.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/src/be/dist/server/controllers/item/create-item-controller.js:4:12)
    at CsvParserStream.<anonymous> (/src/be/dist/server/controllers/item/create-item-controller.js:71:38)
    at CsvParserStream.emit (events.js:210:5)
    at CsvParserStream.emit (/src/be/node_modules/@fast-csv/parse/build/src/CsvParserStream.js:48:22)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at CsvParserStream.Readable.push (_stream_readable.js:224:10)
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 26)
`

**Comment by ludeknovy** [comment]
Hi @SonaliSihra, thanks for rising this up and for all the included infos.

From the logs I can see there is an issue with a connection to the mongo db.

Could you check if the mongo db is running?

The item should be marked as "failed" instead of "in progress" in this case. I will look at it and fix it.

**Comment by ludeknovy** [comment]
Ok, I was able to reproduce the mongo connection issue. Will try to fix it soon.

**Comment by ludeknovy** [comment]
@SonaliSihra please try it again with updated [docker-compose file](https://github.com/ludeknovy/jtl-reporter/blob/master/docker-compose.yml). It should be fixed.

**Comment by SonaliSihra** [comment]
> Ok, I was able to reproduce the mongo connection issue. Will try to fix it soon.

Thanks for the confirmation @ludeknovy , please share a timeline for the fixes if possible because right now I'm relying on it. Also, it is a must required tool that i needed for a very long time. Appreciate your hard work!!!

**Comment by ludeknovy** [comment]
@SonaliSihra as stated in my previous comment, the connection issue should be solved

**Comment by SonaliSihra** [comment]
> @SonaliSihra as stated in my previous comment, the connection issue should be solved

@ludeknovy i tried and it is working fine now. Thank you so much for fixing it up. Also, can you please confirm if it is possible to show total RPS in the dashboard ?

**Comment by ludeknovy** [comment]
@SonaliSihra thanks for confirmation!

Total RPS you can get in report detail, it's named as "Throughput".
