### ISSUE TITLE
Server Agent Monitor memory load not displayed in Monitoring stats

### ISSUE THREAD

**Issue by chesterT** [ludeknovy/jtl-reporter#93]
**Describe the bug**
Memory load is not displayed in Monitoring stats

**To Reproduce**
upload a test run with a csv file containing server cpu and memory load

**Expected behavior**
Memory load should be displayed in Graph 

**LOGS jtl-reporter-master_be_1 **
{"message":"Starting new item processing for scenario: AddToBasket","level":"info"}
{"level":"info","message":"POST /api/projects/ScriptMetricsTests/scenarios/AddToBasket/items 200 13ms","meta":{}}
{"message":"Starting KPI file streaming and saving to Mongo with dataId: de96114d-6df7-4c95-8a3b-083720698afb","level":"info"}
{"level":"info","message":"GET /api/projects/ScriptMetricsTests/scenarios/AddToBasket/processing-items 200 12ms","meta":{}}
{"level":"info","message":"GET /api/projects/ScriptMetricsTests/scenarios/AddToBasket/trends 200 36ms","meta":{}}
{"message":"Error while parsing data: not a number","level":"error"}
{"message":"Error while parsing data: not a number","level":"error"}
{"message":"Error while parsing data: not a number","level":"error"}
{"message":"Error while parsing data: not a number","level":"error"}
{"message":"Parsed 2200 records in 0.118 seconds","level":"info"}
{"message":"Item: 614db488-96ae-44d7-b75e-ca54a1ee35d2 processing finished","level":"info"}
{"level":"info","message":"GET /api/projects/ScriptMetricsTests/scenarios/AddToBasket/processing-items 200 2ms","meta":{}}
{"level":"info","message":"GET /api/projects/ScriptMetricsTests/scenarios/AddToBasket/items?limit=15&offset=0 200 4ms","meta":{}}
{"level":"info","message":"GET /api/projects 200 3ms","meta":{}}
{"level":"info","message":"GET /api/projects/ScriptMetricsTests/scenarios/AddToBasket/items/614db488-96ae-44d7-b75e-ca54a1ee35d2?token=undefined 200 21ms","meta":{}}
{"level":"info","message":"GET /api/projects/ScriptMetricsTests/scenarios/AddToBasket/items/614db488-96ae-44d7-b75e-ca54a1ee35d2/custom-chart-settings 200 2ms","meta":{}}
{"message":"Starting new item processing for scenario: AddToBasket","level":"info"}
{"level":"info","message":"POST /api/projects/ScriptMetricsTests/scenarios/AddToBasket/items 200 14ms","meta":{}}
{"message":"Starting KPI file streaming and saving to Mongo with dataId: 98697e85-34cc-47ff-b0ec-bf5bb377b189","level":"info"}
{"message":"Error while parsing data: not a number","level":"error"}
{"message":"Error while parsing data: not a number","level":"error"}
{"message":"Error while parsing data: not a number","level":"error"}
{"message":"Parsed 2200 records in 0.177 seconds","level":"info"}
{"message":"Item: b60b347e-c1ff-42c2-996e

**Screenshots**

![testRunDashboard](https://user-images.githubusercontent.com/5553445/136038552-60b32c7c-2a7a-422b-b6a1-89b2383f275c.png)
-dc47f9ddc54d processing finished","level":"info"}

![chart](https://user-images.githubusercontent.com/5553445/136038528-cd5af850-57de-4a82-9dc7-677d930d3aa0.png)

**Sample CSV**
[SAlogs_testAgentIP_4444.csv](https://github.com/ludeknovy/jtl-reporter/files/7286452/SAlogs_testAgentIP_4444.csv)
.
**Did JtlReporter make you happay in any way?**
Test run comparison , helps us identify errors in our builds

**Comment by ludeknovy** [comment]
fixed in v4.
