### ISSUE TITLE
I cannot login in a fresh installed v4 environment

### ISSUE THREAD

**Issue by MoritzSalein** [ludeknovy/jtl-reporter#97]
After a fresh installation of v4 I try to open the web frontend with  http://localhost:2020/. I get a empty white window and in the browser URL shows http://localhost:2020/login?returnUrl=%2Fdashboard as the opened page.
Do you know what I've did wrong?

**Comment by ludeknovy** [comment]
Hi @MoritzSalein. Did you do the install on the same machine where you already have v3 running?

It sounds like this issue? https://github.com/ludeknovy/jtl-reporter/discussions/96#discussioncomment-1612606
If that does not help, please send me logs from the backend service.

**Comment by MoritzSalein** [comment]
@ludeknovy Yes, I run it on the same machine as the v3. But I clone the repository to a new folder and not in the same folder as the v3.
My solution are the steps as you described in another post: https://github.com/ludeknovy/jtl-reporter/discussions/96#discussioncomment-1612932

For troubleshooting, there are the error list while the page wasn't loaded.
![image](https://user-images.githubusercontent.com/83296020/142895135-6c6b3e29-a8f8-4bd5-8da8-499af2f5722b.png)
![image](https://user-images.githubusercontent.com/83296020/142895177-942b2a6a-55cd-4c65-a86c-76d97f2a69a3.png)

Thank you and the issue can be closed.
