### ISSUE TITLE
v4 Network transfer bit rate is wrong in the scenario trends graph

### ISSUE THREAD

**Issue by MoritzSalein** [ludeknovy/jtl-reporter#98]
The network transfer bit rate is wrong in the scenario trends graph. In the scale are only.

V4 graph:
**
![image](https://user-images.githubusercontent.com/83296020/142896992-eeaaad3e-3f29-465a-8a60-c4cd24810d57.png)
** 
The overview of the same run means: 
![image](https://user-images.githubusercontent.com/83296020/142897871-71bd32cd-fe7c-4217-bd42-f6a4665770d5.png)

V3 graph (sorry for the different look, because the picture was edited for documentation):
![image](https://user-images.githubusercontent.com/83296020/142897512-c47e92dc-0b55-4cef-8f07-6ddde1c75d36.png)

**Comment by ludeknovy** [comment]
should be fixed.
